migrated linting from tslint to eslint
ngworker/lumberjack pull request #102
Opened 2021-12-20 16:48 UTC by patelvimal

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2021-12-21 15:19 UTC, LayZeeDK commented
Things to consider when reviewing and accepting this PR:
1. Our GitHub workflows are currently broken. @NachoVazquez is working on a fix.
2. If we can run angular-eslint locally and get rid of all lint errors, we will be willing to merge your PR even before (1) is fixed.
3. Mostly, default rules would be good. But we are using a few opinionated lint settings such as member ordering and `readonly` requirement.

2021-12-27 04:10 UTC, NachoVazquez commented
Hi, @patelvimal sorry for the delay in reviewing this PR. I'll take a look tomorrow. Thanks for contributing.

2022-01-02 03:16 UTC, LayZeeDK requested changes
Remaining lint errors, see files with check annotations under the *Files changed* tab.

2022-01-02 03:16 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-root.module.ts
> +    // eslint-disable-next-line  @typescript-eslint/no-non-null-assertion
issue: This conversion doesn't match the previous setting. It should have an `eslint-disable` as well as an `eslint-enable` comment.

2022-01-02 03:16 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver-root.module.ts
>      maybeNgModuleFromParentInjector: LumberjackHttpDriverRootModule = null as any
issue: We need to disable the no null and no any lint rules for these lines

2022-01-02 03:16 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts
>    const [_, level, timestamp, taggedScopeWithEndingSpace = '', scope = '', message] =
issue: Lint error for the `_` variable.

2022-01-02 13:44 UTC, patelvimal commented on libs/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts
>    const [_, level, timestamp, taggedScopeWithEndingSpace = '', scope = '', message] =
This is showing as a warning not error. However there are many warning lint is showing should be fixed those as well?

2022-01-02 13:46 UTC, patelvimal commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-root.module.ts
> +    // eslint-disable-next-line  @typescript-eslint/no-non-null-assertion
DId not understand this comment, can you ellaborate what needs to be done? Initally it was disabled that's why I disabled in eslint as well.

2022-01-02 13:46 UTC, patelvimal commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver-root.module.ts
>      maybeNgModuleFromParentInjector: LumberjackHttpDriverRootModule = null as any
ok, let me apply those rules as well.

2022-01-04 16:57 UTC, NachoVazquez commented
Hey @patelvimal !

Thanks again for the help. I'm actually doing the same migration in another branch where I'm migrating to Angular 13

However, I prefer to have two separate PR and then I can rebase on yours.

Here is a list of the files that I think you are still missing to migrate:

### Sonar

- `tools/scripts/configure-report-paths.mjs`
- `sonar-project.properties`

### Lumberjack App

- `apps/lumberjack-app/src/app/app-logger.service.ts`
- `apps/lumberjack-app/src/app/app.components.ts`

### Internal

- `libs/internal/test-util/src/lib/error-throwing-driver/error-throwing-driver.module.ts`
- `libs/internal/test-util/src/lib/noop-driver/noop-driver.module.ts`
- `libs/internal/test-util/src/lib/object-driver/object-driver.module.ts`
- `libs/internal/test-util/src/lib/spy-driver/spy-driver.module.ts`
- `libs/internal/test-util/src/lib/spy-driver/spy.driver.ts`
- `libs/internal/test-util/src/lib/type-checking/is-class.ts`

Although, some of the files I marked are affected by rules that I didn't override. Just verify that lints are passing

2022-01-04 17:01 UTC, NachoVazquez requested changes

2022-01-08 13:16 UTC, patelvimal commented on .eslintrc.json
> +  "root": true,
@NachoVazquez I have updated the eslint configuration based on this, please have a look into the PR.

2022-01-08 13:21 UTC, patelvimal commented
> Hey @patelvimal !
> 
> Thanks again for the help. I'm actually doing the same migration in another branch where I'm migrating to Angular 13
> 
> However, I prefer to have two separate PR and then I can rebase on yours.
> 
> Here is a list of the files that I think you are still missing to migrate:
> 
> ### Sonar
> * `tools/scripts/configure-report-paths.mjs`
> * `sonar-project.properties`
> 
> ### Lumberjack App
> * `apps/lumberjack-app/src/app/app-logger.service.ts`
> * `apps/lumberjack-app/src/app/app.components.ts`
> 
> ### Internal
> * `libs/internal/test-util/src/lib/error-throwing-driver/error-throwing-driver.module.ts`
> * `libs/internal/test-util/src/lib/noop-driver/noop-driver.module.ts`
> * `libs/internal/test-util/src/lib/object-driver/object-driver.module.ts`
> * `libs/internal/test-util/src/lib/spy-driver/spy-driver.module.ts`
> * `libs/internal/test-util/src/lib/spy-driver/spy.driver.ts`
> * `libs/internal/test-util/src/lib/type-checking/is-class.ts`
> 
> Although, some of the files I marked are affected by rules that I didn't override. Just verify that lints are passing

Thanks @NachoVazquez ,  I have  checked again and all the above files are passing the ESLint rules.

2022-01-11 03:01 UTC, NachoVazquez commented
Hi @patelvimal!

I think that the sonar files are still using tslint. If you look inside the files you will notice that there are references to using tslint as the linter.

Performing a search inside both of the files mentioned above will point you in the right direction.

Thanks again!

2022-01-11 06:36 UTC, patelvimal commented
Hi @NachoVazquez 
Thanks for pointing out that, you were right. I have removed all those references and also some tslint packages as well.
Please review it and let me know if any changes required.

2022-03-12 20:05 UTC, NachoVazquez approved these changes

2022-03-12 20:13 UTC, merged

2022-03-13 16:37 UTC, patelvimal commented
Thanks @NachoVazquez for review .