feature/139/use provide and with factory functions
ngworker/lumberjack pull request #144
Opened 2022-11-07 22:26 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Moduleless (standalone) applications have to import Lumberjack modules to make Lumberjack work instead of a more suitable solution like provider factory functions.

Issue Number: #139 

## What is the new behavior?

Lumberjack can easily be used in standalone applications using the new provider factory functions. These are created for the Lumberjack Core and built-in drivers

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2022-11-29 23:04 UTC, LayZeeDK requested changes

2022-11-29 23:04 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.providers.ts
> +};
issue: Rename to `lumberjackHttpDriverProvider`.

2022-11-29 23:04 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.providers.ts
> +import { Provider } from '@angular/core';
issue: Rename this file to `provide-lumberjack-http-driver.ts`

2022-11-29 23:04 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/logging/lumberjack.service.ts
> +@Injectable({ providedIn: 'root' })
issue: Must not be injectable without calling `provideLumberjack` or importing `LumberjackModule.forRoot`. Add `LumberjackService` to the `providers` array returned by `provideLumberjack` and `LumberjackRootModule.providers` instead.
```suggestion
@Injectable()
```

2022-11-29 23:51 UTC, NachoVazquez commented on packages/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-root.module.ts
> +@NgModule()
It should make more sense in the next commit after using the provide functions directly.

2022-11-29 23:52 UTC, NachoVazquez commented on packages/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver.module.ts
> +        },
It should make more sense, in the next commit.

2022-11-29 23:52 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.ts
>      return {
Excellent suggestion!

2022-11-30 00:05 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.providers.spec.ts
> +    imports: [HttpClientModule],
Yep, I need to wait for Angular 15 for this.

2022-11-30 00:06 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.providers.ts
> +  // provide HTTPClient when Angular 15 is released.
Once the branch is merged, I'll take care of this.

2022-11-30 00:14 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.providers.ts
> +export function provideLumberjackHttpDriverWithOptions(options: LumberjackHttpDriverOptions): Provider[] {
What would that look like?

Are we passing a function to provide the config or option?

2022-11-30 00:32 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.providers.ts
> +export function provideLumberjackHttpDriverWithOptions(options: LumberjackHttpDriverOptions): Provider[] {
Got it!

2022-12-11 01:09 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.providers.spec.ts
> +    imports: [HttpClientModule],
For the nx 15 branch I mean

2023-03-12 21:23 UTC, santoshyadavdev commented on packages/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver.providers.ts
> +export function provideLumberjackConsoleDriver(config: Partial<LumberjackConsoleDriverConfig> = {}): Provider[] {
👌

2023-03-12 21:23 UTC, santoshyadavdev commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/provide-lumberjack-http-driver.spec.ts
> +import { O } from 'ts-toolbelt';
Just from the readability perspective, can we use Object rather than O? Also, why this package? It waslast released 2 years ago?

2023-03-12 21:23 UTC, santoshyadavdev commented on packages/ngworker/lumberjack/src/lib/configuration/provide-lumberjack.ts
> +export function provideLumberjack(options?: LumberjackOptions): Provider[] {
great job on this.

2023-03-15 23:36 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/provide-lumberjack-http-driver.spec.ts
> +import { O } from 'ts-toolbelt';
Good point. I'll change that.

The package is great, it has a lot of useful types.

If you know any alternative I don't mind swapping up, but this one has served me well :)

2023-03-16 20:37 UTC, LayZeeDK requested changes

2023-03-16 20:37 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +This is our Moduless API, ready for everyone using Angular >v14.
issue: it's called *standalone*, not *moduless*.

2023-03-16 20:37 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +Module-full:
issue: it can be called *classic*, not *module-full*.

2023-03-16 20:37 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +Module-less:
issue: it's called *standalone*, not *module-less*.

2023-03-16 20:37 UTC, LayZeeDK commented on package.json
> +    "ts-toolbelt": "^9.6.0",
issue: pin the version
```suggestion
    "ts-toolbelt": "^9.6.0",
```
run `yarn install` afterwards to update the lockfile

2023-03-16 20:37 UTC, LayZeeDK commented on package.json
> +    "ts-toolbelt": "^9.6.0",
question: are we really adding a type utility dependency to use it in one test?

2023-03-16 20:37 UTC, LayZeeDK commented on package.json
> +    "ts-toolbelt": "^9.6.0",
question: what's the TypeScript version range compatibility for this ancient package?

2023-03-16 20:37 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +export function withOptions(options: LumberjackHttpDriverOptions): LumberjackHttpDriverConfiguration<'options'> {
issue: it needs to be called `withHttpOptions` or `withHttpConfig` to prevent name clashing with other entry points/packages.

2023-03-16 20:37 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.ɵproviders];
issue: we must not depend on the `ɵproviders` property. This name is unstable and changes from Angular version to Angular version without warning.

2023-03-16 20:37 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +): (Provider | EnvironmentProviders)[] {
issue: we should return `EnviromentProviders` only. Use [makeEnvironmentProviders](https://angular.io/api/core/makeEnvironmentProviders) to create them from regular `Provider`s.

2023-04-08 22:35 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +This is our Moduless API, ready for everyone using Angular >v14.
```suggestion
This is our standalone API, ready for everyone using Angular >v14.
```

2023-04-15 11:42 UTC, LayZeeDK commented on packages/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-root.module.ts
> +@NgModule()
Ah, I see. This is now provided by `provideLumberjackConsoleDriver` whereas it used to be in the `providers` metadata for `LumberjackConsoleDriverRootModule`.
```typescript
{
  provide: lumberjackLogDriverToken,
  useClass: LumberjackConsoleDriver,
  multi: true,
},
```

2023-04-15 12:16 UTC, LayZeeDK requested changes

2023-04-15 12:16 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/provide-lumberjack-http-driver.ts
> +}
suggestion: Can we use `makeEnvironmentProviders` internally in `makeLumberjackHttpConfiguration` only? It makes it easier for the consumers of `makeLumberjackHttpConfiguration` even if they only exist in our codebase.
```suggestion
function makeLumberjackHttpConfiguration<Kind extends LumberjackHttpDriverConfigurationKind>(
  kind: Kind,
  providers: Provider[]
): LumberjackHttpDriverConfiguration<Kind> {
  return {
    kind,
    providers: makeEnvironmentProviders(providers),
  };
}

export function withHttpConfig(config: LumberjackHttpDriverConfig): LumberjackHttpDriverConfiguration<'config'> {
  return makeLumberjackHttpConfiguration('config', [
    {
      provide: lumberjackHttpDriverConfigToken,
      deps: [lumberjackLogDriverConfigToken],
      useFactory: (logDriverConfig: LumberjackLogDriverConfig): LumberjackHttpDriverInternalConfig => ({
        ...logDriverConfig,
        identifier: LumberjackHttpDriver.driverIdentifier,
        ...config,
      }),
    },
  ]);
}

export function withHttpOptions(options: LumberjackHttpDriverOptions): LumberjackHttpDriverConfiguration<'options'> {
  return makeLumberjackHttpConfiguration('options', [
    {
      provide: lumberjackHttpDriverConfigToken,
      deps: [lumberjackLogDriverConfigToken],
      useFactory: (logDriverConfig: LumberjackLogDriverConfig): LumberjackHttpDriverInternalConfig => ({
        ...logDriverConfig,
        identifier: LumberjackHttpDriver.driverIdentifier,
        ...options,
      }),
    },
  ]);
}
```

2023-04-15 12:16 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/provide-lumberjack-http-driver.ts
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
suggestion: Combine with suggested change in `lumberjack-http-driver.provider.ts`
```suggestion
return [provideHttpClient(), makeEnvironmentProviders([lumberjackHttpDriverProvider]), configuration.providers];
```

2023-04-15 12:16 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +});
suggestion: Let's add the same HTTP config shown above
```suggestion
bootstrapApplication(AppComponent, {
  providers: [
    provideLumberjack(),
    provideLumberjackConsoleDriver(),
    provideLumberjackHttpDriver(
      withHttpConfig({
        levels: [LumberjackLevel.Error],
        origin: 'ForestApp',
        retryOptions: { maxRetries: 5, delayMs: 250 },
        storeUrl: '/api/logs',
      })
    ),
  ],
});
```

2023-04-15 12:16 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> -Only this time we are passing our custom configuration object.
```suggestion
or

```typescript
@NgModule({
  ...,
  providers: [
    ...,
    provideLumberjack(), provideLumberjackConsoleDriver(), provideLumberjackHttpDriver(withHttpConfig({
      levels: [LumberjackLevel.Error],
      origin: 'ForestApp',
      retryOptions: { maxRetries: 5, delayMs: 250 },
      storeUrl: '/api/logs',
    }))
    ...
  ],
  ...
})
export class AppModule {}
```

2023-04-15 20:51 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/configuration/provide-lumberjack-http-driver.ts
> +}
Thanks for all the suggestions; you make my life a happy ride ❤️ 

You are the best!

2023-04-15 20:57 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> -Only this time we are passing our custom configuration object.
Nice! That makes sense!

2023-04-15 20:58 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> +});
Awesome!

2023-04-16 07:05 UTC, LayZeeDK requested changes

2023-04-16 07:05 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
question: How can we allow the consumer to provide HttpClient features like [`withInterceptors`](https://angular.io/api/common/http/withInterceptors) and [`withXsrfConfiguration`](https://angular.io/api/common/http/withXsrfConfiguration)?

2023-04-16 07:05 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/configuration/provide-lumberjack.ts
> +export function provideLumberjack(options?: LumberjackOptions): Provider[] {
issue: We need to cover new public API entries with public API tests in `configuration-api.spec.ts`. This goes for all entries added in this pull request.

2023-04-16 12:20 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
That's a good point; I know interceptors defined in [lazy loaded routes will work](https://netbasal.com/using-the-angular-http-client-in-angular-v15-f4bec3c11926), but I have my doubts about what happens if you redefined it in the `bootsrapApplication` or `AppModule`.

I will experiment with this, but providing our API to configure it is likely more useful.

We have always had this problem, now that I think about it.

2023-04-16 13:47 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
After experimenting (I could remember how dependency injection would work in this case), the developer can overwrite the interceptor configuration by defining themselves the `provideHttpClient`

I tried putting the `provideHttpClient` before and after the `provideLumberjackHttpDriver` :

```ts
bootstrapApplication(AppComponent, {
  providers: [
    provideHttpClient(
      withInterceptors([
        (req, next) => {
          console.log('are interceptors working?');
          // We can use the inject() function inside this function
          // For example: inject(AuthService)
          return next(req);
        },
      ])
    ),
    provideLumberjack('Cypress' in window ? cypressLumberjackOptions : undefined),
    provideLumberjackHttpDriver(
      withHttpOptions({
        origin: 'ForestApp',
        retryOptions: { maxRetries: 1, delayMs: 250 },
        storeUrl: '/api/logs',
      })
    ),
    provideLumberjackConsoleDriver(),
  ],
});
``` 

and 

```ts
bootstrapApplication(AppComponent, {
  providers: [
    provideLumberjack('Cypress' in window ? cypressLumberjackOptions : undefined),
    provideLumberjackHttpDriver(
      withHttpOptions({
        origin: 'ForestApp',
        retryOptions: { maxRetries: 1, delayMs: 250 },
        storeUrl: '/api/logs',
      })
    ),
    provideLumberjackConsoleDriver(),
    provideHttpClient(
      withInterceptors([
        (req, next) => {
          console.log('are interceptors working?');
          // We can use the inject() function inside this function
          // For example: inject(AuthService)
          return next(req);
        },
      ])
    ),
  ],
});
```

2023-04-16 13:50 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/configuration/provide-lumberjack.ts
> +export function provideLumberjack(options?: LumberjackOptions): Provider[] {
thanks for the reminder :)

2023-05-03 18:24 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
Any way we can suport this?
```typescript
bootstrapApplication(AppComponent, {
  providers: [
    provideLumberjack('Cypress' in window ? cypressLumberjackOptions : undefined),
    provideLumberjackHttpDriver(
      withHttpOptions({
        origin: 'ForestApp',
        retryOptions: { maxRetries: 1, delayMs: 250 },
        storeUrl: '/api/logs',
      }),
      withInterceptors([
        (req, next) => {
          console.log('are interceptors working?');
          // We can use the inject() function inside this function
          // For example: inject(AuthService)
          return next(req);
        },
      ]),
    ),
    provideLumberjackConsoleDriver(),
    ),
  ],
});
```
(and other `HttpClient` _features_)

2023-05-03 18:26 UTC, LayZeeDK commented on packages/ngworker/lumberjack/console-driver/src/configuration-api.spec.ts
> +      expect(isClass(sut)).toBeTruthy();
issue: the `isClass` function shouldn't be used. Do we have an `isFunction` or similar?

2023-05-03 18:26 UTC, LayZeeDK requested changes

2023-05-03 18:26 UTC, LayZeeDK commented on packages/ngworker/lumberjack/console-driver/src/configuration-api.spec.ts
> +      expect(isClass(sut)).toBeTruthy();
issue: the `isClass` function shouldn't be used. Do we have an `isFunction` or similar?

2023-05-03 18:26 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/configuration-api.spec.ts
> +      expect(isClass(sut)).toBeTruthy();
issue: the `isClass` function shouldn't be used. Do we have an `isFunction` or similar?

2023-05-04 01:10 UTC, NachoVazquez commented on packages/ngworker/lumberjack/console-driver/src/configuration-api.spec.ts
> +      expect(isClass(sut)).toBeTruthy();
Great catch!

2023-05-04 01:12 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/configuration-api.spec.ts
> +      expect(isClass(sut)).toBeTruthy();
Nice catch!

2023-05-04 01:22 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
Yes, I think we can. Let me give it a try

2023-05-04 01:38 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
Great call here, this makes a beautiful API

2023-05-04 02:11 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
And yes!

We can use the inject function here

```ts
withInterceptors([
        (req, next) => {
          console.log('are interceptors working?');
          // We can use the inject() function inside this function
          // For example: inject(AuthService)
          return next(req);
        },
      ]),
    ```

2023-05-04 02:11 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
This is how I tested it

```ts
const easyToken = new InjectionToken('easy-provider');

bootstrapApplication(AppComponent, {
  providers: [
    {
      provide: easyToken,
      useValue: 'provider-easy',
    },
    provideLumberjack('Cypress' in window ? cypressLumberjackOptions : undefined),
    provideLumberjackConsoleDriver(),
    provideLumberjackHttpDriver(
      withHttpOptions({
        origin: 'ForestApp',
        retryOptions: { maxRetries: 1, delayMs: 250 },
        storeUrl: '/api/logs',
      }),
      withInterceptors([
        (req, next) => {
          const easy = inject(easyToken);
          console.log('are interceptors working?', easy);
          // We can use the inject() function inside this function
          // For example: inject(AuthService)
          return next(req);
        },
      ])
    ),
  ],
});

```

2023-05-04 02:14 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/README.md
> +  return [provideHttpClient(), lumberjackHttpDriverProvider, configuration.providers];
Implementation is done, but I need to update the Readme tomorrow :)

2023-05-14 20:46 UTC, LayZeeDK requested changes
Lint and Bug Issues are reported by SonarCloud.

For some reason, lint issues in `*.spec.ts` files are not reported by SonarCloud, for example this current issue:
```
http-driver\src\lib\configuration\provide-lumberjack-http-driver.spec.ts
    2:10  warning  'HttpInterceptorFn' is defined but never used  @typescript-eslint/no-unused-vars
  141:45  warning  Unexpected any. Specify a different type       @typescript-eslint/no-explicit-any
  141:56  warning  Unexpected any. Specify a different type       @typescript-eslint/no-explicit-any
```

2023-05-15 23:17 UTC, NachoVazquez commented
> Lint and Bug Issues are reported by SonarCloud.
> 
> For some reason, lint issues in `*.spec.ts` files are not reported by SonarCloud, for example this current issue:
> 
> ```
> http-driver\src\lib\configuration\provide-lumberjack-http-driver.spec.ts
>     2:10  warning  'HttpInterceptorFn' is defined but never used  @typescript-eslint/no-unused-vars
>   141:45  warning  Unexpected any. Specify a different type       @typescript-eslint/no-explicit-any
>   141:56  warning  Unexpected any. Specify a different type       @typescript-eslint/no-explicit-any
> ```

Also the ESLint Sonar plugin is not detecting the same stuff as the Cloud

2023-05-15 23:59 UTC, NachoVazquez commented
> Lint and Bug Issues are reported by SonarCloud.
> 
> For some reason, lint issues in `*.spec.ts` files are not reported by SonarCloud, for example this current issue:
> 
> ```
> http-driver\src\lib\configuration\provide-lumberjack-http-driver.spec.ts
>     2:10  warning  'HttpInterceptorFn' is defined but never used  @typescript-eslint/no-unused-vars
>   141:45  warning  Unexpected any. Specify a different type       @typescript-eslint/no-explicit-any
>   141:56  warning  Unexpected any. Specify a different type       @typescript-eslint/no-explicit-any
> ```

It is working now :)

2023-05-22 21:32 UTC, LayZeeDK approved these changes
Approved pending answer of 1 question.

2023-05-22 21:32 UTC, LayZeeDK commented on .github/workflows/ci.yml
> -        yarn nx-cloud record -- yarn nx workspace-lint
question: Where has `nx workspace-lint` been marked as deprecateed?

2023-05-23 06:55 UTC, NachoVazquez commented on .github/workflows/ci.yml
> -        yarn nx-cloud record -- yarn nx workspace-lint
I've received the warning on CLI every time I run the command.

But it is also marked as deprecated on their documentation.

https://nx.dev/packages/nx/documents/workspace-lint#workspace-lint

2023-05-23 06:56 UTC, merged