chore: migrate to latest nx (15.2.1) and angular 15
ngworker/lumberjack pull request #147
Opened 2022-11-25 21:56 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The workspace is using Nx 14.x and Angular 14.x

## What is the new behavior?

The workspace uses the latest Nx 15.2.x and the latest Angular 15.0.x

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

2022-11-25 22:02 UTC, LayZeeDK commented
Please also migrate to Cypress 11.0.

2022-11-29 23:06 UTC, LayZeeDK requested changes

2022-11-29 23:06 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/logging/lumberjack.service.ts
>     * The registered log drivers.
issue: `@Injectable({ providedIn: LumberjackRootModule })` is deprecated behavior as of Angular 15.

2022-11-29 23:19 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts
> +  httpTestingController.expectNone(options.storeUrl);
Nope, this was a headache to transform, but now the last request never happens.

2022-11-29 23:19 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/operators/retry-with-delay.operator.ts
>    );
Yes, `retryWhen` is deprecated.

2022-12-06 20:14 UTC, LayZeeDK commented on packages/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts
> +  httpTestingController.expectNone(options.storeUrl);
issue: document this change for the HTTP driver

2022-12-06 20:17 UTC, LayZeeDK requested changes

2022-12-06 20:17 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/logging/lumberjack.service.ts
>     * The registered log drivers.
issue: This isn't an appropriate replacement. See https://github.com/ngworker/lumberjack/pull/144#discussion_r1035369964

2023-02-15 19:22 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts
> +      providers: [LumberjackLogFactory, LumberjackTimeService],
suggestion: Use `LumberjackModule.forRoot` instead of providing each dependency individually
```suggestion
      imports: [LumberjackModule.forRoot()],
```
(also add a relative import at the top of the file)

2023-02-15 19:25 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/time/lumberjack-time.service.spec.ts
> +      providers: [LumberjackTimeService],
suggestion: Use `LumberjackModule.forRoot` instead of providing each dependency individually
```suggestion
      imports: [LumberjackModule.forRoot()],
```
(also add a relative import at the top of the file)

2023-02-15 19:27 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/configuration/lumberjack-root.module.ts
> +    LumberjackTimeService,
nit: Can we list these providers in alphabetical order?
```suggestion
    LumberjackLogDriverLogger,
    LumberjackLogFactory,
    LumberjackLogFormatter,
    LumberjackService,
    LumberjackTimeService,
 ```

2023-02-17 01:03 UTC, NachoVazquez commented on packages/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.ts
> +   * When the last retry fails, the error is caught and the log is discarded.
Oh wow, great catch

2023-03-07 20:40 UTC, santoshyadavdev approved these changes
Just had few questions, otherwise looks good to me.

2023-03-07 20:40 UTC, santoshyadavdev commented on package.json
> +    "node": "18.12.1",
Do we really want to use node 18, 16 is still supported.

2023-03-07 20:40 UTC, santoshyadavdev commented on packages/ngworker/lumberjack/src/lib/time/lumberjack-time.service.ts
> +@Injectable()
Just wondering why we are dropping providedIn: 'root'. Is this expected? 
Do we really want to rely on module to provide this service, considering optional ngModules

2023-03-07 20:40 UTC, santoshyadavdev commented on packages/ngworker/lumberjack/src/lib/logging/lumberjack-log-factory.ts
> +@Injectable()
Is it removed because LumberjackLogFactory will be used internally?

2023-03-07 20:40 UTC, santoshyadavdev commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.ts
> +@Injectable()
Just to understand, this is dropped because this service will be used internally and not exposed to consumers?

2023-03-08 00:20 UTC, NachoVazquez commented on package.json
> +    "node": "18.12.1",
We have migrated because 18 is the new LTS.

2023-03-08 00:27 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/time/lumberjack-time.service.ts
> +@Injectable()
We are dropping the `provideIn: 'root'` because this service should only be available when importing the' LumberjackModule'. This guarantee that the whole Lumberjack system works as a whole.

On the other hand, there is a PR blocked by this one to support both Modulfull and Modurless APIs.

2023-03-08 00:30 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/logging/lumberjack-log-factory.ts
> +@Injectable()
It is dropped because we want all Lumberjack services to be provided once and only if the `LumberjackModule` is imported or the `provideLumberjack` function is used.

2023-03-08 00:31 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.ts
> +@Injectable()
> It is dropped because we want all Lumberjack services provided once and only if the LumberjackModule is imported or the provideLumberjack function is used.

@LayZeeDK I remember this suggestion came from you. Do you want to add anything?

2023-03-08 22:29 UTC, merged