feature: extract lumberjack core into an agnostic library
ngworker/lumberjack pull request #154
Opened 2023-05-17 13:39 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Lumberjack is a highly extensible and configurable logging library for Angular.

But why stop there?

## What is the new behavior?

`@webworker/lumberjack` is a framework-agnostic logging library; it powers `ngworker/lumberjack` and enables the creation of any framework-specific lumberjack implementation like Qwik, Solid, or React.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

Although nothing changes for `@ngworker/lumberjack`, this refactoring should introduce a major version.

2023-08-10 19:22 UTC, LayZeeDK requested changes
Partial review of latest commits.

2023-08-10 19:22 UTC, LayZeeDK commented on packages/webworker/lumberjack/src/lib/formatting/lumberjack-format-log.ts
> + * "<level> <timestamp> [<scope>] <message>". If the scope is not provided, it will be omitted.
suggestion: Rephrase
```suggestion
 * Format a {@link LumberjackLog} into a string of the format:
 * `"<level> <timestamp> [<scope>] <message>"`
 * If a scope is not provided, it will be omitted.
 *
 * @remarks Default function used by Lumberjack to format Lumberjack log.
```

2023-08-10 19:22 UTC, LayZeeDK commented on packages/webworker/lumberjack/src/lib/formatting/lumberjack-log-formatter-result.ts
> + * Represents what a LumberjackLogFormatter->formatLog function will return.
suggestion: Rephrase
```suggestion
The return type of `LumberjackLogFormatter#formatLog`.
```

2023-08-10 19:22 UTC, LayZeeDK commented on packages/webworker/lumberjack/src/lib/logging/create-lumberjack.ts
> + * Factory function that creates a Lumberjack core system object.
nit: Use imperative tense.
```suggestion
* Create a Lumberjack core system object.
```

2023-08-10 19:22 UTC, LayZeeDK commented on packages/webworker/lumberjack/src/lib/logging/lumberjack.ts
> +>;
issue: This is inverted. The type should be declared up front and returned by `createLumberjack`, not the other way around.

2023-08-10 19:22 UTC, LayZeeDK commented on packages/webworker/lumberjack/src/lib/logging/create-lumberjack-log-factory.ts
> + * Factory function to create a set of functions for building Lumberjack logs with different levels.
nit: Use imperative tense.
```suggestion
 * Create a set of functions for building Lumberjack logs of distinct levels.
```

2023-08-10 19:22 UTC, LayZeeDK commented on packages/webworker/lumberjack/src/lib/logging/lumberjack-log.builder.ts
> +    getUnixEpochTicks: () => number = () => new Date().valueOf()
question: Do we have an integration test that replaces `getUnixEpochTicks`?

2023-08-15 10:34 UTC, NachoVazquez commented on packages/webworker/lumberjack/src/lib/formatting/create-lumberjack-log-formatter.ts
> +>;
I agree!

2023-08-15 10:45 UTC, NachoVazquez commented on packages/webworker/lumberjack/src/lib/formatting/create-lumberjack-log-formatter.ts
> +  };
It does make sense to return just a function. I was returning an object to keep it consistent with the other `create*` factory functions on the workspace.

If you think is ok to just return a function, I'm happy with that.

2023-08-15 10:51 UTC, NachoVazquez commented on packages/webworker/lumberjack/src/lib/formatting/create-lumberjack-log-formatter.ts
> +  };
These are the two possibilities:

**Returning an object**

```ts
  const logFormatter = createLumberjackLogFormatter({ config, getUnixEpochTicks });
 
  const { log, formattedLog } = logFormatter.formatLog(lumberjackLog);
```

**Returning a function**

```ts
  const formatLog = createLumberjackLogFormatter({ config, getUnixEpochTicks });

  const { log, formattedLog } = formatLog(lumberjackLog);
```

2023-08-15 10:55 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/logging/lumberjack.service.ts
> +export class LumberjackService<TPayload extends LumberjackLogPayload | void = void> implements Lumberjack<TPayload> {
In my article about [Plugin Architecture](https://dev.to/this-is-angular/plugin-architecture-for-angular-libraries-using-dependency-injection-5d8k) I use the terms core system and orchestrator.

Any of those terms resonates with you?

2023-08-15 11:11 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/logging/lumberjack.service.ts
> +export class LumberjackService<TPayload extends LumberjackLogPayload | void = void> implements Lumberjack<TPayload> {
I'm going with `LumberjackOrchestrator`. But we can change later.

2023-08-15 11:22 UTC, NachoVazquez commented on packages/webworker/lumberjack/src/lib/logging/lumberjack-log.builder.ts
> +    getUnixEpochTicks: () => number = () => new Date().valueOf()
In most tests, we use the `fakeTime.getUnixEpochTicks` if that's what you were thinking.

2023-08-15 11:24 UTC, NachoVazquez commented on CONTRIBUTING.md
> +| `react`      | A project that is based on the React framework.   |
That's a good question. I wonder if we need it because the agnostic core should be enough. But a `nestjs` tag and NestJS SDK will be there.

2023-10-30 07:43 UTC, LayZeeDK requested changes
Request changes

2023-11-05 20:25 UTC, NachoVazquez commented on packages/internal/angular/test-util/src/lib/time/fake-time.service.ts
> +import { LumberjackTimeService } from '@lumberjackjs/angular';
For the agnostic core, I have replaced it with a `getUnixEpochTicks` function that can be passed to the `createLumberjack` factory function.

By default it uses the `() => new Date().valueof()`

This is the complete method signature

```ts
export function createLumberjack<TPayload extends LumberjackLogPayload | void = void>({
  drivers,
  config,
  getUnixEpochTicks = () => new Date().valueOf(),
}: LumberjackDependencies<TPayload>): Lumberjack<TPayload> 

```

2023-11-05 22:03 UTC, NachoVazquez commented on packages/docs/lumberjack-docs-app/docs/log-drivers/log-drivers.md
> +import { LumberjackConsoleDriverModule } from '@lumberjackjs/angular/console-driver';
That is a good catch, but I fear I must do a profound rewrite of the docs. Also, write down the migration guide.

2023-11-05 22:34 UTC, NachoVazquez commented on packages/docs/lumberjack-docs-app/docs/log-drivers/log-drivers.md
> +import { LumberjackConsoleDriverModule } from '@lumberjackjs/angular/console-driver';
Yeah, I checked, and the docs are in bad shape. I will rewrite them next weekend.

2023-11-05 22:35 UTC, NachoVazquez commented on packages/docs/lumberjack-docs-app/docs/log-drivers/log-drivers.md
> +import { LumberjackHttpDriverModule } from '@lumberjackjs/angular/http-driver';
I will rewrite the whole documentation next week.

2023-11-05 22:36 UTC, NachoVazquez commented on packages/internal/angular/console-driver/test-util/src/lib/spy-console/spy-console.module.ts
> +import { lumberjackConsoleToken } from '@lumberjackjs/angular/console-driver';
Yes, this no longer exists; it was deleted in a follow-up commit.

2023-11-05 22:37 UTC, NachoVazquez commented on packages/internal/angular/console-driver/test-util/src/lib/spy-console/spy-console.service.ts
> +import { LumberjackConsole } from '@lumberjackjs/angular/console-driver';
The spy-console was rewritten, and it is completely agnostic now.

2023-11-05 22:38 UTC, NachoVazquez commented on packages/lumberjackjs/angular/console-driver/src/index.ts
> + * Public API surface of @lumberjackjs/angular/console-driver
This not longer exists.

2023-11-05 22:40 UTC, NachoVazquez commented on packages/lumberjackjs/angular/http-driver/src/index.ts
> + * Public API surface of @lumberjackjs/angular/http-driver
This is outdated. It was addressed in a follow-up commit.

2024-01-05 06:20 UTC, LayZeeDK commented
See #188

2024-01-05 06:20 UTC, closed without merging