chore: migrate to ecmascript private functions
ngworker/lumberjack pull request #156
Opened 2023-05-26 18:06 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[x] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Our source code uses using TypeScript `private` modifier for class fields.

Fixes: #142 

## What is the new behavior?

Our source code uses EcmaScript private properties (#)

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

2023-05-26 20:47 UTC, LayZeeDK requested changes
Great work! Some changes needed.

2023-05-26 20:47 UTC, LayZeeDK commented on README.md
> +  constructor(#lumberjack: LumberjackService) {}
issue: This example uses invalid syntax. It should be
```suggestion
  readonly #lumberjack = inject(LumberjackService);
```

2023-05-26 20:47 UTC, LayZeeDK commented on README.md
> +  readonly #payload: LogPayload = {
issue: This change is not equivalent. It should be
```suggestion
  static readonly #payload: LogPayload = {
```

2023-05-26 20:47 UTC, LayZeeDK commented on README.md
> +  readonly #payload: LogPayload = {
issue: The `helloForest` method below should be
```typescript
  helloForest = this.createInfoLogger('Hello, Forest!').withPayload(AppLogger.#payload).build();
```

2023-05-26 20:47 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/formatting/format-log-driver-error.ts
> +  const thrownErrorMessage = (error as Error).message ?? String(error);
question: Why are lint resolutions include in this PR and weren't they already merged from a different PR?

2023-05-26 20:47 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts
> +    formattedLogPattern.exec(formattedLog) ?? [];
question: Why are lint resolutions include in this PR and weren't they already merged from a different PR?

2023-05-26 20:47 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.ts
> +    const formattingErrorMessage = (formatError as Error).message ?? String(formatError);
question: Why are lint resolutions include in this PR and weren't they already merged from a different PR?

2023-05-26 20:47 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts
> +  #driverLogStrategyMap = {
issue: Let's keep `readonly`
```suggestion
  readonly #driverLogStrategyMap = {
```

2023-05-26 20:47 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts
> +  };
issue: The properties of this map aren't read-only. Why was it introduced?

2023-05-26 20:56 UTC, NachoVazquez commented
Awesome, I'll get these in the night 😊

2023-05-26 22:00 UTC, NachoVazquez commented on README.md
> +  constructor(#lumberjack: LumberjackService) {}
This is weird; I think I got a merge issue. But great catch!

2023-05-26 22:01 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/formatting/format-log-driver-error.ts
> +  const thrownErrorMessage = (error as Error).message ?? String(error);
I think I got a bad merge conflict somewhere.

2023-05-26 22:02 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts
> +  };
You are right; I will freeze the object. But the main problem is that there is no direct translation to the previous syntax. This was the closest solution I could think of.

2023-05-26 23:30 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/formatting/format-log-driver-error.ts
> +  const thrownErrorMessage = (error as Error).message ?? String(error);
But, no, when I look at main it had the problem already. It seems Sonar sometimes can't detect the issues.

2023-05-26 23:34 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts
> +    formattedLogPattern.exec(formattedLog) ?? [];
No, idea, I thought it was a rebase issue, but it seems that Sonar just caught it now.

2023-05-26 23:34 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.ts
> +    const formattingErrorMessage = (formatError as Error).message ?? String(formatError);
No, idea, I thought it was a rebase issue, but it seems that Sonar just caught it now.

2023-05-26 23:40 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts
> +  };
You cannot say for example

```ts
readonly #[LumberjackLevel.Critical] = criticalLogDriverLoggingStrategy;
```

2023-05-26 23:44 UTC, NachoVazquez commented on README.md
> +  constructor(#lumberjack: LumberjackService) {}
Nah , I think it was just an overlook on my side :)

2023-05-26 23:46 UTC, NachoVazquez commented on README.md
> +  readonly #payload: LogPayload = {
These are the kind of catches that only you pull through, fantastic review!

2023-05-26 23:49 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts
> +  };
The alternative would be something like

```ts
readonly #critical = criticalLogDriverLoggingStrategy;
```

But we would lose the type-safety.

2023-05-29 20:13 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts
> +  };
That is unfortunate. What do you think of 031c3586a154a24263f102c9366a5996c17c5d14 though?

2023-05-29 20:16 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/formatting/format-log-driver-error.ts
> +  const thrownErrorMessage = (error as Error).message ?? String(error);
Please put `||` -> `??` operator replacements in a separate PR.

2023-05-29 20:16 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts
> +    formattedLogPattern.exec(formattedLog) ?? [];
Please put `||` -> `??` operator replacements in a separate PR.

2023-05-29 20:16 UTC, LayZeeDK commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.ts
> +    const formattingErrorMessage = (formatError as Error).message ?? String(formatError);
Please put `||` -> `??` operator replacements in a separate PR.

2023-05-29 20:27 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/formatting/format-log-driver-error.ts
> +  const thrownErrorMessage = (error as Error).message ?? String(error);
I can do that, but It won't pass the pipeline. Are you ok with forcing the merge?

2023-05-29 20:27 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-format-log.spec.ts
> +    formattedLogPattern.exec(formattedLog) ?? [];
I can do that, but It won't pass the pipeline. Are you ok with forcing the merge?

2023-05-29 20:27 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/formatting/lumberjack-log-formatter.service.ts
> +    const formattingErrorMessage = (formatError as Error).message ?? String(formatError);
I can do that, but It won't pass the pipeline. Are you ok with forcing the merge?

2023-05-29 20:33 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts
> +  };
I like it. The problem that this approach is that we lose the `TPayload` type if we don't pass it down to the `LumberjackLogDriverLoggingStrategy>. It will fall back to void every time.

2023-05-29 20:44 UTC, NachoVazquez commented on packages/ngworker/lumberjack/src/lib/log-drivers/lumberjack-log-driver-logger.ts
> +  readonly #loggingStrategies: Readonly<Record<LumberjackLogLevel, LumberjackLogDriverLoggingStrategy>> = {
It is probably enough to do the following

```suggestion
  readonly #loggingStrategies: Readonly<Record<LumberjackLogLevel, LumberjackLogDriverLoggingStrategy<TPayload>>> = {
```

2023-06-01 19:29 UTC, LayZeeDK submitted a review, later dismissed

2023-06-06 08:17 UTC, LayZeeDK approved these changes

2023-06-06 09:36 UTC, merged