Guard http driver from use wihout root
ngworker/lumberjack pull request #16
Opened 2020-09-28 22:31 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`HttpDriverModule` can be imported directly, which currently doesn't make any sense.

Issue Number: N/A

## What is the new behavior?

Consumers must import using `HttpDriverModule.forRoot`.

## Does this PR introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Other information

2020-09-28 23:13 UTC, LayZeeDK requested changes
I added an additional guard for the `HttpDriverRootModule` with accompanying test. Please review.

2020-09-28 23:13 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +      providers: [{ provide: HttpDriverConfigToken, useValue: { ...defaultLogDriverConfig, ...config } }],
I think this is what we want.

```suggestion
      providers: [
        {
          deps: [LogDriverConfigToken],
          provide: HttpDriverConfigToken,
          useFactory: (logDriverConfig: LogDriverConfig): HttpDriverConfig => ({
            ...logDriverConfig,
            ...config,
          }),
        },
      ],
```

2020-09-29 00:08 UTC, NachoVazquez commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.spec.ts
> +const expectNgModuleToBeGuarded = <TModule>(ngModuleType: Type<TModule>) => {
I was thinking about that.

2020-09-29 05:46 UTC, LayZeeDK requested changes

2020-09-29 05:46 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +          useFactory: httpDriverConfigFactory,
Why do we have to introduce yet another injection token? Didn't this approach work?
[`3a814aa` (#16)](https://github.com/ngworker/lumberjack/pull/16/commits/3a814aa40db1c05321f23df7d0fe9bc7c9b4d866)

2020-09-29 14:09 UTC, NachoVazquez commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +          useFactory: httpDriverConfigFactory,
AoT builds don't allow for lambda expressions; that's something I have faced before.
https://angular.io/guide/aot-compiler#no-arrow-functions

AoT builds also require to export factory functions.

Once this change is made, we don't have direct access to the `HttpDriverConfig` parameter; we need to inject it.

But since it is the same token we are providing,  we will create a cyclic dependency. That's why I created a temp token to bypass this issue.

2020-09-29 14:13 UTC, NachoVazquez commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +          useFactory: httpDriverConfigFactory,
The documentation closes as this 

> In version 5 and later, the compiler automatically performs this rewriting while emitting the .js file.

However, I did get a build error.

2020-09-29 21:38 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +          useFactory: httpDriverConfigFactory,
It wasn't the same token.

```ts
      providers: [
        {
          deps: [LogDriverConfigToken],
          provide: HttpDriverConfigToken,
          useFactory: (logDriverConfig: LogDriverConfig): HttpDriverConfig => ({
            ...logDriverConfig,
            ...config,
          }),
        },
      ],
```

We were providing `HttpDriverConfigToken` with a dependency on `LogDriverConfig`.

Lambda expressions should be fine. Which build was failing? Application build or library build?

2020-09-29 22:03 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +          useFactory: httpDriverConfigFactory,
I see that the library build is the one failing. Let me look into this.

2020-09-29 22:07 UTC, LayZeeDK commented
I added some CI-related changes.

2020-09-29 22:31 UTC, NachoVazquez commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +          useFactory: httpDriverConfigFactory,
But you are right, probably providing the class `HttpDriverConfig` could do the trick.

2020-09-29 22:53 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +          useFactory: httpDriverConfigFactory,
Please elaborate 🙂

2020-09-29 23:19 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/log-drivers/http-driver/http-driver.module.ts
> +          useFactory: httpDriverConfigFactory,
I figured out a solution that doesn't require introducing the third injection token.

2020-09-29 23:21 UTC, LayZeeDK approved these changes

2020-09-29 23:46 UTC, merged

2020-09-29 23:53 UTC, LayZeeDK commented
@all-contributors please add @LayZeeDK for infra.

2020-09-29 23:54 UTC, LayZeeDK commented
@all-contributors please add @LayZeeDK for infra

2020-09-29 23:54 UTC, LayZeeDK commented
@all-contributors please add me for infra.