perf: ⚡️ create secondary entrypoints for drivers
ngworker/lumberjack pull request #17
Opened 2020-09-30 01:16 UTC by NachoVazquez

BREAKING CHANGE: drivers now need to be imported from their respective paths

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ x ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Core functionality and drivers are bundled together in a single entrypoint

Issue Number: N/A

## What is the new behavior?

Core functionality is imported from the main entrypoint, and secondary entrypoints are created for each driver.

## Does this PR introduce a breaking change?

```
[ x ] Yes
[ ] No
```

Currently, drivers are imported from the main entrypoint:

```typescript
import { ConsoleDriverModule, HttpDriverModule } from '@ngworker/lumberjack';
```

Now, drivers must be imported from their own entrypoints.

```typescript
import { ConsoleDriverModule } from '@ngworker/lumberjack/console-driver';
import { HttpDriverModule } from '@ngworker/lumberjack/http-driver';
```

## Other information

2020-09-30 06:01 UTC, LayZeeDK requested changes
First round. I still need to take a closer look at the package structure and configurations.

2020-09-30 15:16 UTC, NachoVazquez commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
I would have to export the `HttpDriver` and `ConsoleDriver`, though.

I'm not sure if I want drivers exposed. It will probably be necessary if a consumer wants to test the library as a third party.

2020-09-30 18:59 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
If we can't write these tests from another package without a reference to those classes, we probably need to expose them. Certainly, the Angular modules should be imported from the package name. I know this is only a test, but this is especially important in the runtime files. Always use the package name, not relative paths.

Let me take another look at these tests.

2020-09-30 19:11 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
If there's no way around it, we could add an `/*-driver/internal` import path.

2020-09-30 19:43 UTC, LayZeeDK requested changes

2020-09-30 19:43 UTC, LayZeeDK commented on projects/ngworker/lumberjack/console-driver/package.json
> +}
This one is probably fine since we don't expect the console driver to have any dependencies except for browser APIs.

2020-09-30 19:43 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +{
This configuration needs to be converted into a *sub-module* configuration like [this sample](https://github.com/ng-packagr/ng-packagr/blob/master/integration/samples/secondary/sub-module/package.json).

```suggestion
{
  "name": "@ngworker/lumberjack/http-driver",
  "private": true,
```

I don't know if we *have* to add a `"version"` declaration.

2020-09-30 19:43 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/common/http": "^10.0.14"
We need to list all dependencies that are used in this sub-module.
```suggestion
    "@angular/common/http": "^10.0.14",
    "@angular/core": "^10.0.14",
    "rxjs": "^6.5.5"
```

2020-09-30 19:43 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/common/http": "^10.0.14"
`@angular/common/http` is not a separate NPM package so it's not a valid dependency to list here. We should list `@angular/common` here, but remove it from our primary entry point and remove it from the `imports` metadata option of `LumberjackModule`. That import doesn't make sense since we don't have any declarations in that Angular module.

2020-09-30 19:54 UTC, NachoVazquez commented on projects/ngworker/lumberjack/http-driver/package.json
> +{
From reading the docs, I would believe it automatically keeps the version in sync; I don't think we need to add it.

2020-09-30 20:03 UTC, NachoVazquez commented on projects/ngworker/lumberjack/console-driver/package.json
> +}
I will add the name and mark it as private just to be consistent.

2020-09-30 20:21 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
So this test is a very narrow integration test suite. I would like to split this test suite into multiple test suites in another PR.

2020-09-30 20:22 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
Regarding the imports, change the driver Angular module imports to use the package import paths. Keep relative import paths for the drivers for now.

2020-09-30 20:53 UTC, LayZeeDK commented on projects/ngworker/lumberjack/console-driver/package.json
> +}
In the ng-packagr, this configuration turns the console driver into what's known as a *secondary entry point*, whereas the new configuration for the HTTP driver makes it a *sub-module*. `@ngworker/lumberjack` is the *primary entry point*. Each have different purposes.

I don't think it's necessarily about consistency. It's about what is needed. In our case, we need to separate peer dependencies between the primary entry point and the HTTP driver package, so it has to be a sub-module.

Secondary entry point should be the default, so let's keep the console driver package as a secondary entry point, that is leave this configuration alone.

2020-09-30 21:59 UTC, NachoVazquez commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
I wasn't able to create the `lumberjack/*-driver/_internal` path, not quite sure why. 

For the moment, I added the drivers to the public_api, and I'll try to figure it out later on how to create a `private_api`.

2020-09-30 22:11 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
I'm still wondering what the best approach is. I've been thinking whether it makes sense for people to be able to replace the driver providers at runtime or in tests as you suggested.

2020-09-30 22:28 UTC, NachoVazquez commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
I don't think that it would happen very often, but if they provide an internal driver, they may want to test the type of every available driver, including theirs.

That may be a valid use-case.

2020-10-01 00:16 UTC, NachoVazquez commented on projects/ngworker/lumberjack/console-driver/package.json
> +}
Good to know! `ng-packagr` docs are a bit short regarding advance usages.

2020-10-01 10:48 UTC, LayZeeDK commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
Of course, there's a risk in exposing the drivers in the public API. Once they're there, we have to maintain them and keep breaking changes to a minimum. However, they shouldn't have anything concerning in their public APIs since they will just be implementing the `LogDriver` API.

So what do you think? Should we put the driver classes in the public API?

2020-10-01 14:45 UTC, NachoVazquez commented on projects/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +import { HttpDriver } from '../../http-driver/src/http.driver';
It won't hurt. I tried to keep the drivers out because they are unnecessary, but their API should be highly stable.

Let's add them. It won't compromise the system behavior.

2020-10-01 21:56 UTC, LayZeeDK requested changes
Please remove the CI changes from this branch.

2020-10-01 23:26 UTC, NachoVazquez commented
> Please remove the CI changes from this branch.

I did!

2020-10-02 00:21 UTC, LayZeeDK approved these changes

2020-10-02 01:36 UTC, merged