build: migrate to ngx-deploy-npm v8
ngworker/lumberjack pull request #198
Opened 2024-01-19 22:58 UTC by dianjuar

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

Update ngx-deploy-npm to 8.0.0.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

More information about the changes and their motivation can be found on this [blog post](https://dev.to/dianjuar/whats-coming-to-ngx-deploy-npm-v8-23gn)

2024-01-20 01:44 UTC, NachoVazquez commented
Thanks @dianjuar! I will check this in the morning.

2024-01-21 14:29 UTC, NachoVazquez requested changes
I have a small nitpick but this is of great help, and thanks for creating the ngx-deploy-npm library!

2024-01-21 14:29 UTC, NachoVazquez commented on packages/ngworker/lumberjack/project.json
> +        "postTargets": ["ngworker-lumberjack:build", "ngworker-lumberjack:github", "ngworker-lumberjack:publish"]
nitpick: we don't need to add the `ngworker-lumbjerack:build` to the `postTargets` since it is a dependency of `ngworker-lumberjack:publish`

2024-01-22 15:09 UTC, dianjuar commented on packages/ngworker/lumberjack/project.json
> +        "postTargets": ["ngworker-lumberjack:build", "ngworker-lumberjack:github", "ngworker-lumberjack:publish"]
You need it.
`@jscutlery/semver` recently [updated](https://github.com/jscutlery/semver/pull/771) its documentation to be more descriptive about the behavior of `postTargets`

> The specified targets will be executed as is without triggering any dependencies. It will not trigger the target's dependsOn, and Nx caching is not considered.

This means that you need to rebuild the target dependencies to be able to execute their dependencies. Otherwise, they are just not going to execute the dependent targets.

2024-01-22 15:16 UTC, dianjuar commented on packages/ngworker/lumberjack/project.json
> +        "postTargets": ["ngworker-lumberjack:build", "ngworker-lumberjack:github", "ngworker-lumberjack:publish"]
You may be interested in seeing other `jscutlery/semver` and `ngx-deploy-npm@8.0.0` adoptions:

`jscutlery/semver` -> [migrate to ngx-deploy-npm@8.0.0](https://github.com/jscutlery/semver/pull/772)
ngx-deploy-npm [itself](https://github.com/bikecoders/ngx-deploy-npm/blob/main/packages/ngx-deploy-npm/project.json#L80) (yes, ngx-deploy-npm uses itself to publish to NPM)

2024-01-22 15:29 UTC, NachoVazquez commented on packages/ngworker/lumberjack/project.json
> +        "postTargets": ["ngworker-lumberjack:build", "ngworker-lumberjack:github", "ngworker-lumberjack:publish"]
Oh great to know, I was not aware. Awesome, I will republish your branch to allow Sonar to run and it will be ready to merge, thanks again!

2024-01-23 13:24 UTC, closed without merging