chore: 🤖 add angular-versions-action to ci pipeline
ngworker/lumberjack pull request #20
Opened 2020-10-12 06:10 UTC by NachoVazquez

- this change should allow testing the lib source code with different
angular versions

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ x ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Lumberjack is being tested over the current angular version (10.0.x)

Issue Number: N/A

## What is the new behavior?

Lumberjack is tested over different version of Angular (8.0.x, 9.0.x, 10.0.x)

## Does this PR introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Other information

2020-10-12 16:25 UTC, LayZeeDK commented
It's not happy about https://github.com/ngworker/lumberjack/blob/master/tsconfig.base.json#L17

2020-10-12 16:35 UTC, NachoVazquez commented
> It's not happy about https://github.com/ngworker/lumberjack/blob/master/tsconfig.base.json#L17

Yes, I took a quick look at it. I think we will have to also modify the ts.config in the action. 

Maybe we should rename the action to `angular-version-terraform` or something like that. I'm not happy with the current name. 

Anyway, I'll work on it, later today.

2020-10-16 07:19 UTC, LayZeeDK commented
Just remove the budgets from angular.json.

2020-10-16 16:45 UTC, NachoVazquez commented
> Just remove the budgets from angular.json.

I fixed that one, we have a second one now, I'm testing locally.

This is a related issue.

https://github.com/angular/angular-cli/issues/14888#

2020-10-16 19:27 UTC, LayZeeDK requested changes

2020-10-16 19:27 UTC, LayZeeDK commented on projects/ngworker/lumberjack/console-driver/src/console-driver.module.spec.ts
> +  const [consoleDriver] = (TestBed.get(LogDriverToken) as unknown) as LogDriver[];
This is a problem. `TestBed.get` is deprecated since Angular version 9 and might be removed in Angular version 12. Maybe we should wrap it in a function and look for whichever is available. Let me try that.

2020-10-16 19:27 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
Why is it `8.1.0` and not `8.0.0`?

2020-10-16 19:27 UTC, LayZeeDK commented on tsconfig.base.json
> +    "module": "esnext",
Is this a requirement for the Angular versions action? We should write that as a caveat in the action's README.

2020-10-16 21:08 UTC, LayZeeDK commented on projects/ngworker/lumberjack/console-driver/src/console-driver.module.spec.ts
> +  const [consoleDriver] = (TestBed.get(LogDriverToken) as unknown) as LogDriver[];
Added the `resolveDependency` test utility.

2020-10-16 21:23 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
We should always use the latest patch version. There are often annoying mistakes in the early versions of each major release.

2020-10-16 21:26 UTC, NachoVazquez commented on tsconfig.base.json
> +    "module": "esnext",
It is a requirement for Angular version 8 and 9.

`es2020` is not supported for their typescript  versions.

I could terraform the `tsconfig` in the `angular-versions-action` but I think that `esnext` includes `es2020`

2020-10-16 21:35 UTC, LayZeeDK commented on tsconfig.base.json
> +    "module": "esnext",
Let's leave it for now.

2020-10-16 21:41 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
That was my intention with using 8.0.6 (latest patch version in 8.0.*), but it contains the referred bug.

It only gets solve after `8.1.0`.

2020-10-16 21:43 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
I see. Let's try 8.0.3.

2020-10-16 21:48 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
This conversation is somehow coupled to `angular-versions-action`, and the way I chose the dependencies matching a key (`8.0.0`, `9.0.0`, etc).

To be on the same page, what do you think is the expected behavior when using 

```
 - name: Use Angular version ${{ matrix.angular-version }}
        uses: ngworker/angular-versions-action@v1.2.0
        with:
          angular_version: ${{ matrix.angular-version }}
```

With version `8.0.0`.

What dependencies should be used?

2020-10-16 21:50 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
I think the action parameter should say `8.0.x`. Try to use ´@angular/*@8.0.7`, but `@angular-devkit/build-angular@0.800.3`.

2020-10-16 22:07 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
It doesn't work.

`@angular/*/8.0.*` latest version is `8.0.3`

`@angular-devkit/build-angular` is the one that goes to `0.800.6` and `@angular/cli` that goes to `8.0.3`

I'll try the different combinations and there are always to test that fails with

```
Error: Expected function not to throw, but it threw TypeError: Cannot read property 'ngMetadataName' of undefined.
            at <Jasmine>
            at UserContext.<anonymous> (http://localhost:9878/_karma_webpack_/webpack:/src/lib/lumberjack.service.isolated.spec.ts:20:38)
...
```

2020-10-16 22:21 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
Okay, let's use 8.0.3 and 0.800.3.

2020-10-16 23:28 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
No, is no working.

I updated to the new `angular-versions-action` form though. Now we use it as `8.0.x`, `8.1.x`, etc.

I tried all variations from v8.0.0 to 8.0.3 and 8.0.6 for the CLI, they all failed.

I'll keep investigating to see if there any workaround for it.

2020-10-17 05:25 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
I tried with `@angular/*` with `8.0.3` and the `@angular/cli` and other devDependencies with `8.1.0` and the error persist.

2020-10-17 09:59 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
What about all dependencies as 8.0.3?

2020-10-17 17:59 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        angular-version: [8.1.0, 9.0.0, 10.0.0]
Nop, I tried that too.

2020-10-17 18:40 UTC, LayZeeDK approved these changes

2020-10-17 18:42 UTC, LayZeeDK requested changes

2020-10-17 18:42 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/core": ">=8.0.0 <=latest",
Have we set this in the primary entry point package.json? Should we set Angular 8.1.0?

2020-10-17 18:43 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/core": ">=8.0.0 <=latest",
I alsoo don't think we need to put in latest.

2020-10-17 19:50 UTC, NachoVazquez commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/core": ">=8.0.0 <=latest",
`>=81.0 <=10.0.14` should be good?

2020-10-17 20:27 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/core": ">=8.0.0 <=latest",
I was thinking `>=8.1.0` without an upper version limit.

2020-10-17 20:32 UTC, LayZeeDK requested changes

2020-10-17 20:32 UTC, LayZeeDK commented on projects/ngworker/lumberjack/package.json
> +    "@angular/core": ">=8.1.0 <=10.0.14"
```suggestion
    "@angular/core": ">=8.1.3"
```

2020-10-17 20:32 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/core": ">=8.1.0 <=10.0.14",
```suggestion
    "@angular/core": ">=8.1.3",
```

2020-10-17 20:32 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/common": ">=8.1.0 <=10.0.14",
```suggestion
    "@angular/common": ">=8.1.3",
```

2020-10-17 20:34 UTC, LayZeeDK requested changes

2020-10-17 20:34 UTC, LayZeeDK commented on README.md
> +| > 8.1.0         |   ✅    |
```suggestion
| > 8.1.x         |   ✅    |
```

2020-10-17 20:34 UTC, LayZeeDK commented on README.md
> +| > 9.0.0         |   ✅    |
```suggestion
| > 9.0.x         |   ✅    |
```

2020-10-17 20:34 UTC, LayZeeDK commented on README.md
> +| > 10.0.0        |   ✅    |
```suggestion
| > 10.0.x        |   ✅    |
```

2020-10-17 21:05 UTC, LayZeeDK requested changes

2020-10-17 21:05 UTC, LayZeeDK commented on README.md
> +| > 8.1.0         |   ✅    |
```suggestion
| > 10.0.x        |   ✅    |
| > 9.0.x         |   ✅    |
| > 8.1.x         |   ✅    |
```

2020-10-17 21:06 UTC, LayZeeDK requested changes

2020-10-17 21:06 UTC, LayZeeDK commented on projects/ngworker/lumberjack/http-driver/package.json
> +    "@angular/core": ">=8.1.0 <=10.0.14",
```suggestion
    "@angular/common": ">=8.1.3",
    "@angular/core": ">=8.1.3",
```

2020-10-17 21:48 UTC, LayZeeDK approved these changes

2020-10-17 21:50 UTC, merged