Simplify http driver
ngworker/lumberjack pull request #39
Opened 2020-10-30 01:37 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ x ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ x ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`HttpDriver` is implemented in a faulty and complicated way, not suitable for an example `driver`

Issue Number: N/A

## What is the new behavior?

`HttpDriver` is implemented in a simple more readable way

## Does this PR introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Other information

2020-10-30 23:58 UTC, LayZeeDK requested changes
Missing a test suite for `HttpDriver`.

I created a `retryWithDelay` operator.

2020-11-01 12:17 UTC, LayZeeDK commented
We should consider adding driver options that are passed on to the `retryWithDelay` operator.

2020-11-02 01:00 UTC, LayZeeDK requested changes
You should create test utilities in `http-driver.spec.ts`. There's a lot of boilerplate repetition (read: noise).

2020-11-02 20:37 UTC, LayZeeDK requested changes

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +import { HttpRequest } from '@angular/common/http';
Remove unused import statement.
```suggestion
```

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> + */
```suggestion
/**
 * Call the function the specified number of times.
 */
```

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +}
Extract to test utilities library.

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +  return Array(times).fill(undefined).forEach(fn);
Remove `return` and add `new` to prevent confusion (event though it isn't necessary).
```suggestion
  new Array(times).fill(undefined).forEach(fn);
```

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> + */
If you give this test utility a better name, there's not need for this description.

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +function failHttpWithErrorUnavailable(flush: (...args: any[]) => void) {
Name it something like `respondWith503ServiceUnavailable` and accept a `TestRequest` rather than the flush method.

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +    repeat(retryOptions.attempts - 1, () => {
I think we have a problem here. It shouldn't be `attempts - 1`. Attempts should define the first request + the number of retries. I'm not sure whether this test is playing tricks on me as it's quite complicated to reason about, but is it failing after 1 less attempt than specified? If so, this is a problem in the implementation (which is easily fixed).

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +    });
This function should be given a name and extracted outside of this test case or at the very least in the *Arrange* (setup) section of this test case.

It should read something like `repeat(retryOptions.attempts, expectLogRequest)` to make the test more clear and concise. As a reader, we don't want to be concerned with the details until we need them.

2020-11-02 20:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +    // It cancels any request after the attempts are exhausted
This would be a good test utility name specific to this test case. Something like `expectLogRequestsToStopAfterConfiguredAttempts(attempts: number): void;` if covering the previous function as well, or maybe just `expectRequestToBeAborted(): void;` to cover the final expectation.

2020-11-02 22:47 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +    repeat(retryOptions.attempts - 1, () => {
Yes, I agree. It should be `retryOptions.attempts + 1`.

2020-11-02 23:05 UTC, NachoVazquez commented
A lot of good stuff in those comments!

2020-11-04 19:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +    repeat(retryOptions.attempts - 1, () => {
Attempts = first try + number of retries

2020-11-04 20:11 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +    repeat(retryOptions.attempts - 1, () => {
Exactly, it is already fixed.

2020-11-06 21:31 UTC, LayZeeDK requested changes

2020-11-06 21:31 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/repeat-function.ts
> +export function repeatFunctionCalls(times: number, fn: () => void): void {
Function name doesn't match file name.

2020-11-06 21:31 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/repeat-function.ts
> + */
This description doesn't add any value, so let's remove it.

2020-11-06 21:31 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/repeat-function.ts
> +export function repeatFunctionCalls(times: number, fn: () => void): void {
How about just calling it `repeat` or `repeatSideEffect`?

2020-11-06 21:31 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +}
Functions should be declared before statements to match function hoisting. Even if we convert them to lambdas, TSLint will be sad that we're using them before they're declared.

2020-11-06 21:31 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +        logMethod(httpDriver).call(httpDriver, 'SOME LOG');
How about changing `'SOME LOG'` to `level` so that for example `'debug'` is passed? It would make it easier to debug if one of them fails. In fact, it would be good to replace all instances of `'SOME LOG'`  in this test suite.

2020-11-06 21:31 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +      it('sends a log to the configure url', () => {
```suggestion
      it(`sends a ${level} log to the configured URL`, () => {
```

2020-11-06 21:37 UTC, LayZeeDK requested changes

2020-11-06 21:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +  it('retries after two failures and then succeed', () => {
```suggestion
  it('retries after two failures and then succeeds', () => {
```

2020-11-06 21:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +  it('retries the options number of times after failures and then stop retrying', () => {
```suggestion
  it('retries the specified number of times after failures and then stops retrying', () => {
```

2020-11-06 21:38 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.spec.ts
> +function generateLogEntry(logEntry: string, level: LumberjackLogLevel, origin: string): HttpLogEntry {
Consider renaming this to `createHttpLogEntry`.

2020-11-07 01:56 UTC, NachoVazquez commented on libs/internal/test-util/src/lib/repeat-function.ts
> +export function repeatFunctionCalls(times: number, fn: () => void): void {
I like repeatSideEffect.

2020-11-08 15:37 UTC, LayZeeDK approved these changes

2020-11-08 15:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver-config.token.ts
> +  retryOptions: { attempts: number; delayMs: number };
I think that `retryOptions.attempts` should be renamed to `retries` or `maxRetries`.

2020-11-08 15:37 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http.driver.ts
> +      // tslint:disable-next-line: no-non-null-assertion
Where is this one used?

2020-11-08 15:38 UTC, LayZeeDK requested changes
See previous review comments. I accidentally approved.

2020-11-08 16:38 UTC, LayZeeDK requested changes

2020-11-08 19:18 UTC, LayZeeDK approved these changes

2020-11-09 02:12 UTC, merged