feat: 🎸 add prodMode option to config used for configure levels
ngworker/lumberjack pull request #42
Opened 2020-10-31 17:39 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ x ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ x ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ x ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Lumberjack uses undefined as the default value for levels (log everything) at the `LogDriverConfig`

Issue Number: N/A

## What is the new behavior?

Lumberjack config adds a `prodMode` property to `LumberjackLogConfig` that uses as default value Angular `!isDevMode()`

When `prodMode` is on Lumberjack uses Error and Critical as default levels for `LogDriverConfig`. Otherwise, it uses the `Verbose` level as a default.

## Does this PR introduce a breaking change?

```
[ ] Yes
[ x ] No
```

## Other information

2020-10-31 21:04 UTC, LayZeeDK commented
In .NET, the default log level in production is `Information` which means that both `Information`, `Warning`, `Error`, and `Critical` levels are logged.

2020-11-06 22:24 UTC, LayZeeDK requested changes

2020-11-06 22:24 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +  prodMode?: boolean;
Why don't we make this `levels` or `defaultLevels` instead? `prodMode` doesn't tell much about what this option does. This will have huge reprecautions for this PR, so please try this out before we'll discuss the rest of the changes.

2020-11-06 22:29 UTC, LayZeeDK requested changes

2020-11-06 22:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack.module.ts
>    static forRoot(config?: LumberjackLogConfig): ModuleWithProviders<LumberjackRootModule> {
Now that we have multiple options, we should either accept `Partial<LumberjackLogConfig>` or call it `LumberjackOptions` or something like that.

2020-11-07 03:22 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +  prodMode?: boolean;
You are right, option names should be clear about what they do and should not hide unknown behaviors.

2020-11-07 04:15 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +  prodMode?: boolean;
It gets complex, though. I have to wrap the `isDevMode` function in a service for testing reasons. But I'm not sure that I will provide an `InjectionContext` in all the places that I will need that service.

2020-11-08 15:42 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +  prodMode?: boolean;
Still not changed, I see. Did you run into any issues?

2020-11-08 15:54 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +  prodMode?: boolean;
Yes, I may have to use a temp injection token for the config to allow me to use a `factoryProvider` where I can inject the `ProdModeService`

I'm trying to see how to avoid that.

2020-11-08 15:57 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +  prodMode?: boolean;
I'll push what I have so you can see what I mean.

2020-11-09 05:57 UTC, LayZeeDK requested changes

2020-11-09 05:57 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +export const defaultDevelopmentLevels: LumberjackLogConfigLevel = [LumberjackLogLevel.Verbose];
These we shouldn't need to export as part of the library's public API. One of the reasons I'm usually explicit in public API exports instead of using export * from statements.

2020-11-09 05:57 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +export const LumberjackLogOptionsToken: InjectionToken<LumberjackLogOptions> = new InjectionToken(
We have been here before. We have to get rid of this. This is a cop out.

2020-11-09 13:51 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +export const LumberjackLogOptionsToken: InjectionToken<LumberjackLogOptions> = new InjectionToken(
Yeah, it is a temporary patch, until I find how to make it work.

2020-11-14 12:45 UTC, LayZeeDK requested changes

2020-11-14 12:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/index.ts
> +export { LumberjackLogConfigToken, LumberjackLogConfig, LumberjackLogOptions } from './lumberjack-log.config';
I would prefer no barrels internally. Only a public API of a library entry point such as `src/index.ts` should be a barrel. Barrels are a mess and can break compilation and cause circular dependencies, some of which are only caught at runtime with the consumer which is going to really suck.

2020-11-14 12:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
>  export const LumberjackLogConfigToken: InjectionToken<LumberjackLogConfig> = new InjectionToken(
Let's split this file into multiple files:
- `lumberjack-log-config.token.ts`
- `lumberjack-log-options.token.ts`
- `lumberjack-log-config.ts` or `lumberjack-log.config.ts`
- `lumberjack-log-options.ts` or `lumberjack-log.options.ts`
- `default-production-levels.ts`
- `default-development-levels.ts`

2020-11-14 12:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +export const LumberjackLogOptionsToken: InjectionToken<LumberjackLogOptions> = new InjectionToken(
We couldn't figure out a way to do this, so we'll leave it.

2020-11-14 12:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +export const LumberjackLogOptionsToken: InjectionToken<LumberjackLogOptions> = new InjectionToken(
Can we agree on casing of injection token names (not this one)? Why are we using PascalCase? It's just an object, so I would prefer camelCase.

2020-11-14 12:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +  '__TEMP_LUMBERJACK_LOG_OPTIONS__'
We need to normalize these descriptions across the repo.

2020-11-14 12:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +export const defaultDevelopmentLevels: LumberjackLogConfigLevel = [LumberjackLogLevel.Verbose];
See comment for `libs/ngworker/lumberjack/src/lib/configs/index.ts`.

2020-11-14 12:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack-root.module.ts
> +}
We need test coverage for this configuration logic. Either unit tests for these factories and/or integration tests using the `TestBed` with `LumberjackRootModule`.

2020-11-14 15:51 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/configs/lumberjack-log.config.ts
> +export const LumberjackLogOptionsToken: InjectionToken<LumberjackLogOptions> = new InjectionToken(
It makes sense!

2020-11-14 22:50 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack-root.module.ts
> +}
This one is still open.

2020-11-14 23:02 UTC, LayZeeDK requested changes

2020-11-15 15:57 UTC, LayZeeDK approved these changes

2020-11-15 17:25 UTC, merged