fix: handle error-throwing log drivers
ngworker/lumberjack pull request #44
Opened 2020-11-14 14:15 UTC by LayZeeDK

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[x] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Log drivers throwing an error causes Lumberjack to fail.

Issue Number: N/A

## What is the new behavior?

Errors thrown by log drivers are caught and logged using the global `Console#error`.

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information
We have a console driver with the `LumberjackConsole` abstraction, but I did not want to introduce a dependency from the main entry point. Besides, if a library consumer replaced the `LumberjackConsole`, this might cause an additional error.

An alternative would be to collect all thrown errors in an array, then rethrow them after the logging loop has completed so that they could be handled by a global error handler.

2020-11-14 15:44 UTC, NachoVazquez requested changes

2020-11-14 15:44 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.spec.ts
> +        expect(console.error).toHaveBeenCalledTimes(1);
Should we test that the other `drivers` did log correctly and weren't interrupted by the **throwingErrorDriver**?

2020-11-14 15:44 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
Should we add some tests to verify that the error message is printed as expected?

2020-11-14 15:53 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
It will just be a duplicate of the implementation. Not sure it's worth it. I'm much more interested in discussing whether this is how we want to handler it. See PR description.

2020-11-14 16:18 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
On second thought, I will just add a sting literal and looking at the code, there's even a bug hiding in the error message which it can help fix.

2020-11-14 19:44 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
> An alternative would be to collect all thrown errors in an array, then rethrow them after the logging loop has completed so that a global error handler could handle them.

I think this is a better idea. 

I was going to suggest that we might want to do one or the other depending on whether it was in a production environment or not. 

However, I think that the global error handler should be the one responsible for deciding what to do with unhandled exceptions.

2020-11-14 22:31 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
If the error is rethrown from `LumberjackService#log`, it will cause the caller to fail. I would really like to prevent this, but this is something that would require a larger effort and careful design. The only straightforward option I see is returning an observable or a promise from `LumberjackService#log` which I'm not sure is a great design either, at least not exclusively for the reason of handling errors thrown by log drivers.

What do you think we should do?

2020-11-14 23:33 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
In every logging loop, we could store the drivers that worked ok, and the errors from those that failed.

We could then execute a second iteration over those that worked ok, sending the collected errors.

If none worked ok, we `console.error` as we are doing right now. `(base case)`

This would be recursive since errors could arise in the second iteration; however, each recursive call should only use the drivers that had worked for every previous recursive call. That would avoid possible infinite loops.

#### My doubts

This solution adds complexity to the codebase, and I don't know if it is worth it.

2020-11-15 11:50 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
The tracking will take some time to get right, but it should be doable. I'll give it a shot.

2020-11-21 13:32 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
You said you were working on skipping drivers that throw errors, so I implemented the first iteration of handling formatter and time service errors in [LayZeeDK/error-handling/spike](https://github.com/ngworker/lumberjack/blob/LayZeeDK/error-handling-spike/libs/ngworker/lumberjack/src/lib/lumberjack.service.ts).

2020-11-21 23:23 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/lumberjack.service.ts
> +  }
See #46.

2020-11-25 23:37 UTC, NachoVazquez approved these changes

2020-11-25 23:37 UTC, merged