chore: 🤖 update lumberjack base config to angular v11
ngworker/lumberjack pull request #48
Opened 2020-11-30 02:46 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[x] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

The example application is using angular v10 and the workspace is following the matching configuration.

Issue Number: N/A

## What is the new behavior?

The workspace and the application are now in the Angular v11 form.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2020-12-02 00:45 UTC, LayZeeDK requested changes
No changes in TypeScript configurations for workspace, application, or libraries?

2020-12-02 00:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver-root.module.ts
> -    // tslint:enable: no-any no-null-keyword
Why was this removed?
```suggestion
    // tslint:enable: no-any no-null-keyword
```

2020-12-02 00:45 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/http-driver.module.spec.ts
> +
No need for this blank line between constant references even when they reference function expressions. Unless Prettier made you do it 😄
```suggestion
```

2020-12-02 23:31 UTC, LayZeeDK submitted a review, later dismissed

2020-12-02 23:33 UTC, LayZeeDK reviewed
No changes to TypeScript configurations of library projects?

2020-12-02 23:34 UTC, NachoVazquez commented
> No changes to TypeScript configurations of library projects?

I will double check.

2020-12-02 23:59 UTC, LayZeeDK commented on libs/ngworker/lumberjack/tsconfig.lib.json
>      "target": "es2015",
What's the `target` in a fresh Angular 11 workspace?

2020-12-02 23:59 UTC, LayZeeDK commented on libs/ngworker/lumberjack/tsconfig.lib.json
>      "lib": ["dom", "es2018"]
What's the `lib` in a fresh Angular 11 workspace?

2020-12-03 01:47 UTC, NachoVazquez commented on libs/ngworker/lumberjack/tsconfig.lib.json
>      "target": "es2015",
The same.

2020-12-03 01:47 UTC, NachoVazquez commented on libs/ngworker/lumberjack/tsconfig.lib.json
>      "lib": ["dom", "es2018"]
I would take it out then.

2020-12-03 09:18 UTC, LayZeeDK commented on apps/lumberjack-app/src/test.ts
> +import 'zone.js/dist/zone-testing';
Where is import 'zone.js/dist/zone';

2020-12-03 15:48 UTC, NachoVazquez commented on apps/lumberjack-app/src/test.ts
> +import 'zone.js/dist/zone-testing';
What do you mean?

2020-12-03 16:09 UTC, LayZeeDK commented on apps/lumberjack-app/src/test.ts
> +import 'zone.js/dist/zone-testing';
The other test.ts files have this line before zone-testing
import 'zone.js/dist/zone';

2020-12-03 16:13 UTC, NachoVazquez commented on apps/lumberjack-app/src/test.ts
> +import 'zone.js/dist/zone-testing';
I don't think I removed it, but it looks that it is not needed.

2020-12-03 20:23 UTC, LayZeeDK approved these changes
Great job!

2020-12-03 20:25 UTC, merged