feat: 🎸 pass log object to drivers as log method argument
ngworker/lumberjack pull request #49
Opened 2020-12-01 15:56 UTC by NachoVazquez

BREAKING CHANGE: driver authors need to implement the new interface

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Drivers only receive the formatted message on logging disabling more advanced logging capabilities.

Issue Number: N/A

## What is the new behavior?

Drivers receive the formatted message and the raw log object, enabling the possibility to perform more advances functionalities.

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

The `LogDriver` interface has been modified to accept the log object as a second argument. Drivers authors need to adjust their implementation to this new feature.

## Other information

2020-12-06 00:06 UTC, LayZeeDK requested changes
Missing:
1. Make `LumberjackLogger` generic to support custom log properties.
2. Make `LumberjackHttpDriver` and `LumberjackHttpDriverLog` support custom log properties.
3. Make `LumberjackConsoleDriver` output custom or all log properties to the console.

2020-12-06 00:58 UTC, NachoVazquez commented
> Missing:
> 
> 1. Make `LumberjackLogger` generic to support custom log properties.
> 2. Make `LumberjackHttpDriver` and `LumberjackHttpDriverLog` support custom log properties.
> 3. Make `LumberjackConsoleDriver` output custom or all log properties to the console.
> 4. Make LumberjackService generic.
> 5. Add custom log properties in app.

What do you mean by custom log properties?

2020-12-06 11:45 UTC, LayZeeDK commented
A few example custom log properties:
1. Version of Angular.
1. Version/commit hash of app.
1. Session time.
1. Session ID.
1. Active language/locale.

2020-12-06 11:48 UTC, LayZeeDK commented
There are two points of this PR:
1. Give log drivers access to the full log.
1. Allow application to add custom log properties.

Maybe we need a LumberjackLogCreator service which can be replaced by applications. It might also be related to https://github.com/ngworker/lumberjack/issues/5

2020-12-15 22:46 UTC, LayZeeDK requested changes
Add `ScopedLumberjackLogger<TPayload>` to share a scope in a logger service.

Something like:
```ts
export abstract class ScopedLumberjackLogger<TPayload extends Payload | void = void> {
  abstract readonly scope: string;

  constructor(private _lumberjack: LumberjackService<LogPayload>, private _time: LumberjackTimeService) {
    super(lumberjack, time);
  }

  private createLoggerBuilder(level: LumberjackLogLevel, message: string): LumberjackLoggerBuilder<TPayload> {
    return return new LumberjackLoggerBuilder<TPayload>(_this.lumberjack, _this.time, level, message);.withScope(this.scope);
  }
}
```

Example subclass
```ts
export class AppLogger extends ScopedLumberjackLogger<LogPayload> {
  private static payload: LogPayload = {
    angularVersion: VERSION.full,
  };

  scope = 'Forest App';

  constructor(lumberjack: LumberjackService<LogPayload>, time: LumberjackTimeService) {
    super(lumberjack, time);
  }

  forestOnFire = this.createCriticalLogger('The forest is on fire')
    .build();

  helloForest = this.createInfoLogger('HelloForest')
    .withPayload(AppLogger.payload)
    .build();
}
```
`LumberjackLoggerBuilder#withScope` not needed because of the `scope` property used by `ScopedLumberjackLogger`.

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +      it(`should send a LumberjackLog with message "${testMessage}" and level ${level}`, () => {
Don't mention the log message when it's not dynamic.

```suggestion
      it(`sends a ${level} level log`, () => {
```

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +  it('should send the scope when specified', () => {
```suggestion
  it('logs the specified scope', () => {
```

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +    };
Is it possible to use `createCriticalLog` instead? Try this after providing `FakeTimeService` as suggested in an earlier comment.

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +    it('should send the payload when specified in the log function', () => {
```suggestion
    it('logs the specified payload', () => {
```

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +    it('should send the payload when specified in withPayload builder function', () => {
```suggestion
    it('logs the specified static payload', () => {
```

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +    it('should send the scope and payload when both are specified', () => {
```suggestion
    it('logs the specified scope and payload', () => {
```

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.service.spec.ts
> +  warningLogger = this.createWarningLogger('').withScope(TestLogger.scope).build();
Can be simplified by extending `ScopedLumberjackLogger`.

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +      expect(((lumberjackService as unknown) as LumberjackService<TestPayload>).log).toHaveBeenCalledWith(expectedLog);
Try to break test cases into three groups, the three As: *Arrange, Act, Assert*.

That is, leave a blank link between setup and initial state (Arrange), exercising the SUT (Act), and assertions as well as variables used by them (Assert).

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack.service.ts
>          break;
Can we leave the blank line between `driver.log*` and `break`? I like to make control flow statements such as `break`, `continue`, `return`, and `throw` stand out so as to not forget to add them or overlook them.

2020-12-15 22:46 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/object-driver/object.payload.ts
> +  isWorking: boolean;
```suggestion
  readonly isWorking: boolean;
```

2020-12-15 22:46 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/object-driver/object.driver.ts
> +export class ObjectDriver implements LumberjackLogDriver<ObjectPayload> {
Can we rename `Object*` to `Payload*`? `PayloadDriver` and so on? `ObjectPayload` can be renamed to `IsWorkingPayload`.

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.ts
> +  logWarning({ formattedLog }: LumberjackLogDriverLog): void {
I think the HTTP driver should send the payload as well to have an opportunity to dog food this feature and make the HTTP driver more useful out-of-the-box.

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logs/payload.ts
> +export interface Payload {
This should probably be renamed to `LumberjackPayload` or `LumberjackLogPayload` for consistency and to avoid name-clashing in userland code.

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/index.ts
> +export { Payload } from './lib/logs/payload';
Remember to add it to `logs-api.spec.ts` to prevent us from breaking the API later unintended.

2020-12-15 22:46 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logs/lumberjack.log.ts
> +  readonly payload?: TPayload;
The `?` is a problem. The `payload` property must be required if `TPayload` is anything but `void`.

Or am I forgetting something? Maybe log drivers shouldn't assume that a payload exists since the typing is pretty weak to support multiple payload types throughout an application.

2020-12-15 22:46 UTC, LayZeeDK commented on README.md
> +  logCritical({ formattedLog }: LumberjackLogDriverLog): void {
I expect the console driver to do something like pass the log as a second argument and the payload as a third parameter to the `console` methods or the full `LumberjackLogDriverLog` object.

2020-12-16 00:54 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +    spyOn(lumberjackService, 'log').and.callFake(() => {});
Nice!

2020-12-16 23:02 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/logs/lumberjack.log.ts
> +  readonly payload?: TPayload;
This may be a little complex to achieve, but I will try to make it work later.

2020-12-17 23:28 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/logs/lumberjack.log.ts
> +  readonly payload?: TPayload;
The main issue with having a required payload is when having multiple payload types, as you stated. The built-in example is when we want to log driver-errors.

We can loosen a bit of the internal typing, but I'm not very happy with that solution.

2020-12-17 23:35 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logs/lumberjack.log.ts
> +  readonly payload?: TPayload;
You're right. LumberjackService and log drivers can't assume a payload. The type parameter might not consistent across an application.

2020-12-20 15:11 UTC, LayZeeDK requested changes

2020-12-20 15:11 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts
> +        const expectedDriverLog = createDriverLog<HttpDriverPayload>(logLevel, logLevel, '', 'Test', analyticsPayload);
Could we extract parts of the logger builder into a log builder? It could be helpful here. Maybe also to users who want programmatic control through LumberjackService.

2020-12-20 15:11 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/logs/lumberjack-http.log.ts
> +export interface LumberjackHttpLog<TPayload extends Payload | void = void> {
We should send the full LukberjackLog so that the log store gets the timestamp, message, and scope in raw form.

2020-12-20 15:11 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/time/fake-time.service.ts
> +  private fakeDate = new Date('2020-02-02T02:02:02.000Z');
We need a way of specifying this, either through the constructor, a dependency, a property, or a method.

2020-12-23 02:41 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts
> +        const expectedDriverLog = createDriverLog<HttpDriverPayload>(logLevel, logLevel, '', 'Test', analyticsPayload);
I don't see it that clear outside of a testing environment. It is a bit inconvenient the fact of having to inject the `LumberjackTimeService`.

2020-12-27 12:29 UTC, LayZeeDK requested changes

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +      };
```suggestion
      const expectedLog = createLog(level, testMessage, scope, payload);
```

Add `createLog` to `@internal/test-util` imports.

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +      };
```suggestion
      const expectedLog = createLog(level, testMessage, '', payload);
```

Add `createLog` to `@internal/test-util` imports.

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.builder.spec.ts
> +      };
```suggestion
      const expectedLog = createLog(level, testMessage, scope, payload);
```

Add `createLog` to `@internal/test-util` imports.

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/log-drivers/lumberjack-console.driver.ts
> +    this.console.warn(formattedLog, log.payload || '');
We should show that the payload is `undefined`, not empty string.

```suggestion
    this.console.warn(formattedLog, log.payload);
```

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/log-drivers/lumberjack-console.driver.ts
> +    this.console.trace(formattedLog, log.payload || '');
We should show that the payload is `undefined`, not empty string.

```suggestion
    this.console.trace(formattedLog, log.payload);
```

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/log-drivers/lumberjack-console.driver.ts
> +    this.console.info(formattedLog, log.payload || '');
We should show that the payload is `undefined`, not empty string.

```suggestion
    this.console.info(formattedLog, log.payload);
```

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/log-drivers/lumberjack-console.driver.ts
> +    this.console.error(formattedLog, log.payload || '');
We should show that the payload is `undefined`, not empty string.

```suggestion
    this.console.error(formattedLog, log.payload);
```

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/log-drivers/lumberjack-console.driver.ts
> +    this.console.debug(formattedLog, log.payload || '');
We should show that the payload is `undefined`, not empty string.

```suggestion
    this.console.debug(formattedLog, log.payload);
```

2020-12-27 12:29 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/log-drivers/lumberjack-console.driver.ts
> +    this.console.error(formattedLog, log.payload || '');
We should show that the payload is `undefined`, not empty string.

```suggestion
    this.console.error(formattedLog, log.payload);
```

2020-12-27 12:56 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts
> +        const expectedDriverLog = createDriverLog<HttpDriverPayload>(logLevel, logLevel, '', 'Test', analyticsPayload);
I added a `LumberjackLogBuilder` without exposing it for now. Used it in `lumberjack-logger.builder.spec.ts`, but it has one issue to resolve as noted in a comment for that test suite.

Let me know what you think.

2020-12-29 02:30 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts
> +        const expectedDriverLog = createDriverLog<HttpDriverPayload>(logLevel, logLevel, '', 'Test', analyticsPayload);
I built something similar when I was experimenting. My biggest problem with these implementations is that DI can be tricky when used by a `Lumberjack` client.

It is very convenient for test suits though.

2020-12-29 02:42 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts
> +        const expectedDriverLog = createDriverLog<HttpDriverPayload>(logLevel, logLevel, '', 'Test', analyticsPayload);
I'm looking into the Typescript problem. Interesting.

2020-12-29 04:14 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/src/lib/log-drivers/lumberjack-http.driver.spec.ts
> +        const expectedDriverLog = createDriverLog<HttpDriverPayload>(logLevel, logLevel, '', 'Test', analyticsPayload);
I sent a POC for the typing problem. Take a look at it whenever you can.

2021-01-09 23:38 UTC, LayZeeDK requested changes

2021-01-09 23:38 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log.builder.ts
> +type Empty = 'empty' & LumberjackLogPayload;
Can you explain why this one is needed and how it works?

2021-01-10 01:46 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log.builder.ts
> +type Empty = 'empty' & LumberjackLogPayload;
Basically, we just needed some type that we could return in the `withPayload` method that would help to identify when the method was used. 

I tried with `void` but `void` is a special type and it also one of the possible types of the generic argument of `LumberjackLog<TPayload>`.

`Empty` is just a temporary type, I need to use the intersection with LumberjackLogPayload to pass the typescript protection but that's it.

2021-01-10 01:49 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log.builder.ts
> +type Empty = 'empty' & LumberjackLogPayload;
It could be renamed to `Temp` or `PayloadIncluded` if it makes more clear it's usage.

2021-01-10 01:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log.builder.ts
> +type Empty = 'empty' & LumberjackLogPayload;
I don't understand it based on its current name. Can we name it something like `StaticPayload` or `NoPayload` whichever is appropriate?

2021-01-10 12:09 UTC, LayZeeDK requested changes

2021-01-10 12:09 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log-builder.spec.ts
> +  });
Just missing one test case for completeness:
```ts
builder.build(payload)
```
*(dynamic payload, no scope)*

2021-01-10 12:09 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log.builder.ts
> +type StaticPayload = 'static-payload' & LumberjackLogPayload;
Can we use this name and string representation instead? Also rename the type elsewhere in this file.
```suggestion
/**
 * The generic parameter of `LumberjackLogBuilder` is evaluated to this type
 * when the `withPayload` method is used.
 */
type InternalWithStaticPayload = '__LUMBERJACK_INTERNAL_WITH_STATIC_PAYLOAD__' & LumberjackLogPayload;
```

2021-01-11 00:01 UTC, LayZeeDK approved these changes

2021-01-11 04:49 UTC, merged