Throw everything up in the air and see where it lands
ngworker/lumberjack pull request #50
Opened 2020-12-02 22:41 UTC by LayZeeDK

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[x] Code style update (formatting, local variables)
[x] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

1. Terminology is a little confusing and sometimes inconsistent.
1. Naming of files and folders is inconsistent.

Issue Number: N/A

## What is the new behavior?
1. Sticking to agreed terminology and public API export names.
1. Files and folders use a similar structure throughout the codebase

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

**A LOT** of breaking changes

## Other information
Terminology and structure review
- [x] `@ngworker/lumberjack`
- [ ] `@ngworker/lumberjack/console-driver`
- [ ] `@ngworker/lumberjack/http-driver`
- [ ] `@internal/test-util`
- [ ] `@internal/test-util/console-driver`

2020-12-04 20:38 UTC, NachoVazquez requested changes

2020-12-04 20:38 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/README.md
>        ngModule: HttpDriverRootModule,
```suggestion
      ngModule: LumberjackHttpDriverRootModule,
```

2020-12-04 20:59 UTC, LayZeeDK commented on README.md
> +  static forRoot(config?: LumberjackLogDriverConfig): ModuleWithProviders<ConsoleDriverModule> {
No, this is a custom, simplified console log driver implementation for this guide.

2020-12-04 21:01 UTC, LayZeeDK commented on README.md
> +export const consoleDriverConfigToken = new InjectionToken<LumberjackLogDriverConfig>('__CONSOLE_DRIVER__CONFIG__', {
>Should we add consistency to the tokens value like we do we services and modules names?

No, this is a custom, simplified console log driver implementation for this guide. I don't want readers to confuse it with the `LumberjackConsoleDriver` implementation.

2020-12-04 21:03 UTC, LayZeeDK commented on libs/internal/test-util/src/index.ts
> +export * from './lib/error-throwing-driver/error-throwing-driver.config';
I don't think it's worth it for testing drivers. It's easier to differentiate testing ones from public ones just by looking at their names. It's also a lot less typing.

2020-12-05 00:01 UTC, NachoVazquez commented on libs/ngworker/lumberjack/console-driver/src/configuration-api.spec.ts
> +      const sut = LumberjackConsoleDriverModule;
sut stands for what?

2020-12-05 00:03 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/configuration-api.spec.ts
> +      const sut = LumberjackConsoleDriverModule;
Subject Under Test

2020-12-05 14:39 UTC, NachoVazquez approved these changes

2020-12-05 14:46 UTC, merged