[WIP] Add schematics
ngworker/lumberjack pull request #51
Opened 2020-12-05 18:39 UTC by santoshyadavdev

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2020-12-05 21:10 UTC, LayZeeDK commented on nx.json
> +  "npmScope": "nhworker",
```suggestion
  "npmScope": "ngworker",
```

2020-12-05 21:10 UTC, LayZeeDK commented on package.json
> +    "build:lib": "ng build ngworker-lumberjack --prod",
We want to add `README.md` to the bundle.
```suggestion
    "build:lib": "ng build ngworker-lumberjack --prod && npx copy README.md ./dist/ngworker/lumberjack",
```

2020-12-05 21:19 UTC, LayZeeDK commented on angular.json
> +        },
```suggestion
        "build": {
          "builder": "@nrwl/workspace:run-commands",
          "options": {
            "parallel": false,
            "commands": [
              {
                "command": "ng run ngworker-lumberjack:build-package"
              },
              {
                "command": "yarn tsc -p libs/ngworker/lumberjack/tsconfig.schematics.json"
              }
            ]
          },
          "configurations": {
            "production: {
              "commands": [
                {
                  "command": "ng run ngworker-lumberjack:build-package:production"
                },
                {
                  "command": "yarn tsc -p libs/ngworker/lumberjack/tsconfig.schematics.json"
                }
              ]
            }
          }
        },
```

2020-12-05 23:42 UTC, LayZeeDK commented
@santoshyadavdev You can run `yarn ci` to try out the CI pipeline locally, except it only runs with the latest Angular and related dependency versions whereas the CI pipeline runs with all versions of Angular from 9.0 forwards.

2020-12-11 15:06 UTC, LayZeeDK commented
Nx 11 has been released.

2020-12-12 21:34 UTC, LayZeeDK requested changes

2020-12-12 21:34 UTC, LayZeeDK commented on README.md
> +| `console-driver` | boolean (Default=true)  | Yes       | If you want to add consoleDriver to modules import array. |
```
| `console-driver` | boolean (defaults to `true`)  | Yes       | Whether to register `LumberjackConsoleDriver`. |
| `http-driver`    | boolean (defaults to `false`) | Yes       | Whether to register `LumberjackHttpDriver`        |

2020-12-12 21:34 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/collection.json
> +      "description": "Add lumberjack to application"
```suggestion
      "description": "Add Lumberjack to the application."
```

2020-12-12 21:34 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/collection.json
> +      "description": "generate lumberjack files to application"
```suggestion
      "description": "Generate Lumberjack files for the application."
```

2020-12-12 21:34 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/collection.json
> +    "generate": {
Let's leave the generation schematics out of this PR.

2020-12-12 21:34 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/generate/index.ts
> +// import { chain, Rule, Tree, SchematicsException } from '@angular-devkit/schematics';
Let's leave the generation schematics files out of this PR.

2020-12-12 21:34 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/index.ts
> +import { chain, Rule, SchematicsException, Tree } from '@angular-devkit/schematics';
It would be great to have automated tests for our schematics. Do you know how or should we research it together?

2020-12-12 21:34 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/utils/change.ts
> + */
Are these files copied from the Angular repository? Are they not exported by `@angular-devkit/<something>`?

2020-12-12 21:34 UTC, LayZeeDK commented on package.json
> +    "@nrwl/workspace": "^10.4.4",
```suggestion
    "@nrwl/angular": "^11.0.2",
    "@nrwl/workspace": "^11.0.2",
```

2020-12-13 06:39 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/utils/change.ts
> + */
no it's not as of now.

2020-12-13 06:41 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/ng-add/index.ts
> +import { chain, Rule, SchematicsException, Tree } from '@angular-devkit/schematics';
let me add it.

2020-12-13 07:55 UTC, santoshyadavdev commented on package.json
> +    "@nrwl/workspace": "^10.4.4",
After upgrading to the latest started getting error.
An unhandled exception occurred: Builder is not a builder

2020-12-13 07:55 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/generate/index.ts
> +// import { chain, Rule, Tree, SchematicsException } from '@angular-devkit/schematics';
done

2020-12-13 07:55 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/collection.json
> +      "description": "generate lumberjack files to application"
done.

2020-12-13 07:55 UTC, santoshyadavdev commented on README.md
> +| `console-driver` | boolean (Default=true)  | Yes       | If you want to add consoleDriver to modules import array. |
done.

2020-12-15 02:07 UTC, NachoVazquez commented
Hey Santosh, could you add your self to contributors before completing this PR?

`yarn contributors:add`

2020-12-16 13:59 UTC, LayZeeDK commented
Nx 11.0.8 comes with bugfixes for local schematics
![image](https://user-images.githubusercontent.com/6364586/102357970-3a027b80-3faf-11eb-9586-0a9e78116d5d.png)

2021-01-10 00:12 UTC, LayZeeDK requested changes

2021-01-10 00:12 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/schema.json
> +  }
```suggestion
  },
  "required": ["project"]
```

2021-01-10 00:12 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/schema.json
> +      }
How does this work? Shouldn't it be:
```suggestion
      "$default": {
        "$source": "argv",
        "index": 0
      },
```

2021-01-10 00:12 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/schema.ts
> +  skipImport?: boolean;
Not used by schematic.
```suggestion
```

2021-01-10 00:12 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/schema.ts
> +  name: string;
Not used by schematic.
```suggestion
```

2021-01-10 00:12 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/index.spec.ts
> +// /* tslint:disable */
Add `"@angular-devkit/schematics"` to the `no-submodule-imports` rule in `tslint.json`.

2021-01-10 00:12 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/index.spec.ts
> +// });
We need to make the tests run.

2021-01-10 00:14 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/schema.json
> +    },
Is this needed? If so, please change the description.

2021-01-10 11:36 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/ng-add/schema.json
> +  }
We don't need to pass project, ng-add gets the default project if not passed.

2021-01-10 11:36 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/ng-add/schema.json
> +      }
It refers to the default project

2021-01-10 11:37 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/ng-add/schema.ts
> +  name: string;
It is used by find-module.ts , in case users want to skip the import.

2021-01-10 12:11 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/ng-add/index.spec.ts
> +// });
I tried updating dependencies and it still didn't work. Maybe Nx or `decorate-angular-cli.ts` are interfering.

2021-01-14 13:39 UTC, LayZeeDK commented on jest.config.js
> +    '@ngworker/lumberjack': '<rootDir>/libs/ngworker/lumberjack/src/index.ts',
Aaah, nothing like double bookkeeping 🙃

2021-01-30 22:05 UTC, LayZeeDK commented
Closed in favor of #70.

2021-01-30 22:05 UTC, closed without merging