feat: 🎸 rename LumberjackLog property context to scope
ngworker/lumberjack pull request #53
Opened 2020-12-08 05:38 UTC by NachoVazquez

BREAKING CHANGE: LumberjackLog property context was renamed to scope

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes/features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

`LumberjackLog` uses context to denote the origin or scope of an instance log.

Issue Number: N/A

## What is the new behavior?

`LumberjackLog` renames context property to scope.

Scope is a more suitable name for the intent of the property and now context can be used in the future for different purposes like holding correlation ids.

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```
Any client application of custom driver must perform the same property rename across their source code logs.

## Other information

2020-12-08 18:22 UTC, LayZeeDK requested changes
Changes missing in:
- [x] `README.md`
- [ ] `app-logger.service.ts`
- [ ] `lumberjack-module.spec.ts`
- [ ] `lumberjack-format-log.spec.ts`
- [ ] `lumberjack-log-formatter.service.spec.ts`

2020-12-08 20:33 UTC, LayZeeDK requested changes

2020-12-08 20:33 UTC, LayZeeDK commented on README.md
> +  public static logScope = 'Forest App';
Maybe we should just rename it to `context`.

2020-12-08 20:33 UTC, LayZeeDK commented on apps/lumberjack-app/src/app/app-logger.service.ts
> +  public static logScope = 'Forest App';
Maybe we should just rename it to `context`.

2020-12-08 20:53 UTC, NachoVazquez commented on README.md
> +  public static logScope = 'Forest App';
To `context` or to `scope`?

2020-12-08 23:52 UTC, LayZeeDK commented on README.md
> +  public static logScope = 'Forest App';
`scope` of course, my bad 😅

2020-12-09 09:05 UTC, LayZeeDK approved these changes

2020-12-09 21:49 UTC, LayZeeDK commented
Publish a new beta after merging.

2020-12-09 22:03 UTC, merged