feat: 🎸 include required driver configuration `driverGUI`
ngworker/lumberjack pull request #54
Opened 2020-12-18 20:05 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Future filter functionalities need some mechanism to uniquely identify lumberjack drivers. Currently, there are no mechanisms to achieve it.

Issue Number: N/A

## What is the new behavior?

`LumberjackLogDriverConfig` now contains a required property `driverGUI` that uniquely identifies a driver in the system.

## Does this PR introduce a breaking change?

```
[x] Yes
[ ] No
```

Now when configuring a `LumberjackDriver` it is necessary to provide a `driverGUI`.

```ts
@NgModule({
  imports: [
    LumberjackModule.forRoot(),
    LumberjackConsoleDriverModule.withOptions({ driverGUI: LumberjackConsoleDriver.name }),
    LumberjackHttpDriverModule.forRoot({
      levels: [LumberjackLevel.Error],
      origin: 'ForestApp',
      storeUrl: '/api/logs',
      retryOptions: { maxRetries: 5, delayMs: 250 },
      driverGUI: LumberjackHttpDriver.name,
    }),
    // (...)
  ],
  // (...)
})
export class AppModule {}
```

## Other information

2020-12-18 20:49 UTC, LayZeeDK commented
Please don't call it GUI (Graphical User Interface). It's also not a GUID or UUID, so this name is pretty confusing.

2020-12-18 20:51 UTC, LayZeeDK commented
You want users to specify the log driver identifier? Interesting, I though it would be supplied by the log driver. I guess you figure it could be helpful if we eventually enable running multiple instances of the same log driver.

2020-12-18 20:55 UTC, NachoVazquez commented
> Please don't call it GUI (Graphical User Interface). It's also not a GUID or UUID, so this name is pretty confusing.

Yes, it is a temporal name. I'm thinking in `driverIdentifier`.

2020-12-18 20:58 UTC, LayZeeDK commented
Either something like `name` or `identitifer`.

2020-12-18 20:59 UTC, NachoVazquez commented
> You want users to specify the log driver identifier? Interesting, I thought it would be a required property or configuration setting on the log driver. I guess you figure it could be helpful if we eventually enable running multiple instances of the same log driver.
> 
> I think it's a shame to put another required configuration setting on drivers when most users wouldn't need to specify it.

I get your point. I broke a lot of nicely done implementations.

But yeah the main analysis behind that decision was thinking in `featureModules` providing multiple instances of the same driver.

Can you confirm that in that case, I would get both (root and feature) instances??🤔

My assumption is that you would get both.

2020-12-18 21:09 UTC, LayZeeDK commented
Why don't we make the log drivers specifiy a default name/identifier, but allow the user to override it in the log driver config? Then we're future-proof and we don't have to ask the user to pass another setting every time.

2020-12-18 21:40 UTC, NachoVazquez commented
> Why don't we make the log drivers specifiy a default name/identifier, but allow the user to override it in the log driver config? Then we're future-proof and we don't have to ask the user to pass another setting every time.

Good idea!

2021-01-15 21:00 UTC, LayZeeDK requested changes

2021-01-15 21:00 UTC, LayZeeDK commented on apps/lumberjack-app/src/app/app.component.spec.ts
> +        identifier: LumberjackConsoleDriver.name,
Can this be left out? The whole point was that they could have a default identifier and that we should only configure a different identifier if we needed it, for example if we later add multi-instance log drivers or logging with log driver filtering.

2021-01-15 21:16 UTC, NachoVazquez commented on apps/lumberjack-app/src/app/app.component.spec.ts
> +        identifier: LumberjackConsoleDriver.name,
Yes, I only put it there to show that it is possible, but this last refactor made it entirely optional.

2021-01-16 22:01 UTC, LayZeeDK requested changes

2021-01-16 22:01 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
> +    it('gets defaulted options from the log driver config', () => {
```suggestion
    it('gets default options from the log driver config', () => {
```

2021-01-16 22:11 UTC, NachoVazquez commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-config.token.ts
> +    factory: () => ({ ...inject(lumberjackLogDriverConfigToken), identifier: 'LumberjackConsoleDriver' }),
I was using `LumberjackConsoleDriver.name` and I got a few circular dependency warnings. 

I have to double-check why.

2021-01-16 22:15 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver-module.config.ts
> +export type LumberjackHttpDriverModuleConfig = LumberjackLogDriverConfigWithPartialIdentifer;
Does `LumberjackHttpInternalConfig` sound ok for you?

2021-01-16 22:17 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver-module.config.ts
> +export type LumberjackHttpDriverModuleConfig = LumberjackLogDriverConfigWithPartialIdentifer;
Yeah, whatever. The important one is the application-facing one. Apply to our other log drivers as well.

2021-01-16 22:25 UTC, NachoVazquez commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-config.token.ts
> +    factory: () => ({ ...inject(lumberjackLogDriverConfigToken), identifier: 'LumberjackConsoleDriver' }),
Yeah, that won't work.

`LumberjackConsoleDriver -> lumberjackConsoleDriverConfigToken -> LumberjackConsoleDriver`

I could create a new file just for that.

2021-01-16 22:42 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-config.token.ts
> +    factory: () => ({ ...inject(lumberjackLogDriverConfigToken), identifier: 'LumberjackConsoleDriver' }),
Never use `<class | function>#name` for runtime purposes, it will be scrambled by minification.

2021-01-16 22:43 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-config.token.ts
> +    factory: () => ({ ...inject(lumberjackLogDriverConfigToken), identifier: 'LumberjackConsoleDriver' }),
Maybe we could move the factory provider out of the token file.

2021-01-16 22:44 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-config.token.ts
> +    factory: () => ({ ...inject(lumberjackLogDriverConfigToken), identifier: 'LumberjackConsoleDriver' }),
If the name is in a separate file, we will have to put it in a constant which does not seem as closely bound to the log driver class from an application perspective.

2021-01-16 23:02 UTC, NachoVazquez commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-config.token.ts
> +    factory: () => ({ ...inject(lumberjackLogDriverConfigToken), identifier: 'LumberjackConsoleDriver' }),
Let me know what do you think of the solution I just pushed.

2021-01-16 23:06 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-config.token.ts
> +    factory: () => ({ ...inject(lumberjackLogDriverConfigToken), identifier: 'LumberjackConsoleDriver' }),
This does not feel very clean. It has the drawback that I mentioned above as well as a few others:
- We introduce another export per log driver.
- It's verbose.
- It doesn't feel closely bound to the log driver except if the name is read carefully.

If we could extract the factory into the driver module or a separate injection token, it would feel cleaner to an application developer. However, I think we have gone down this road before and using temporary injection tokens introduces accidental complexity.

2021-01-16 23:26 UTC, LayZeeDK requested changes
Use `logDriver.config.identifier` in `formatLogDriverError`.

2021-01-17 00:48 UTC, LayZeeDK requested changes

2021-01-17 00:48 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver.module.ts
> +        },
It would be nice and more clean to extract this default provider into the `LumberjackConsoleDriverRootModule` (and to do the same for other drivers modules).

2021-01-18 19:44 UTC, LayZeeDK requested changes

2021-01-18 19:44 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
> +function createModuleHttpConfig(levels: LumberjackConfigLevels, identifier?: string): LumberjackHttpDriverConfig {
Please revert the name of this one to `createHttpConfig`.

2021-01-18 20:31 UTC, LayZeeDK approved these changes

2021-01-18 20:34 UTC, merged