docs: add inline docs to public APIs
ngworker/lumberjack pull request #59
Opened 2021-01-17 00:36 UTC by LayZeeDK

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Public APIs barely have any inline documentation.

Issue Number: N/A

## What is the new behavior?
All software artifacts exposed in public APIs have inline documentation.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-01-17 01:24 UTC, LayZeeDK commented
@NachoVazquez I don't think we need to expose `lumberjackHttpDriverConfigToken` in the public API. It's only used internally in the HTTP driver package.

2021-01-18 21:26 UTC, NachoVazquez requested changes

2021-01-18 21:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver-internal.config.ts
> + */
This doc section should also be added to the `lumberjack-http-driver.config`

2021-01-18 21:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-logger.service.ts
> +   * Create a logger builder for a critical log with the specified message.
```suggestion
   * Create a logger builder for a debug log with the specified message.
```

2021-01-18 21:26 UTC, NachoVazquez commented
> @NachoVazquez I don't think we need to expose `lumberjackHttpDriverConfigToken` in the public API. It's only used internally in the HTTP driver package.

Could you include this change in this PR?

2021-01-18 21:45 UTC, NachoVazquez approved these changes

2021-01-18 21:48 UTC, merged