Docs/review readme
ngworker/lumberjack pull request #62
Opened 2021-01-20 00:57 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

- Docs don't mention some API elements
- Docs need better wording in some sections
- Docs miss the Community Drivers section

Issue Number: N/A

## What is the new behavior?

- Docs mention all-important API elements
- Docs wording is more accurate
- Docs has a Community Drivers section

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-01-21 10:23 UTC, LayZeeDK commented
Please rebase @NachoVazquez.

2021-01-21 14:20 UTC, NachoVazquez commented
> Please rebase, @NachoVazquez.

✅

2021-01-21 22:11 UTC, LayZeeDK commented on README.md
> +For example, we could use the default logging levels for the console driver and the critical and error levels for the **HTTP driver** as seen in the following example.
*and ... and* is not a good expression.

2021-01-21 22:12 UTC, LayZeeDK commented on README.md
> +For example, we could use the default logging levels for the console driver and the critical and error levels for the **HTTP driver** as seen in the following example.
Where did you catch this obsession with putting words in **bold**? 🤔😄

2021-01-21 22:13 UTC, LayZeeDK commented on README.md
> +A driver module provides configuration and other dependencies to a log driver. It also provides the log driver, making it available to **Lumberjack**.
Again with the **bold**? 🙂

2021-01-21 22:14 UTC, LayZeeDK commented on README.md
> +This is possible because the `ConsoleDriver` has the same configuration options as the `LumberjackLogDriverConfig`. We only have to include the driver identifier since it can not be predefined.
Always use *cannot*.
```suggestion
This is possible because the `ConsoleDriver` has the same configuration options as the `LumberjackLogDriverConfig`. We only have to include the driver identifier since it cannot be predefined.
```

2021-01-21 22:15 UTC, LayZeeDK commented on README.md
> +The driver identifier is a unique string that allows identifying one driver instance from other drivers and even from another lazy-loaded instance of itself.
Let's keep this one out of most of the documentation until we have a use for it.
```sugggestion
```

2021-01-21 22:15 UTC, LayZeeDK commented on README.md
> +The driver identifier is a unique string that allows identifying one driver instance from other drivers and even from another lazy-loaded instance of itself.
Let's keep this one out of most of the documentation until we have a use for it.
```sugggestion
```

2021-01-21 22:16 UTC, LayZeeDK commented on README.md
> +For adding custom settings, see [LumberjackHttpDriver](https://github.com/ngworker/lumberjack/blob/main/libs/ngworker/lumberjack/http-driver/src/lib/lumberjack-http-driver-root.module.ts).
```suggestion
To add custom options, see [LumberjackHttpDriver](https://github.com/ngworker/lumberjack/blob/main/libs/ngworker/lumberjack/http-driver/src/lib/lumberjack-http-driver-root.module.ts).
```

2021-01-21 22:18 UTC, LayZeeDK commented on README.md
> +- [LumberjackFirestoreDriver](https://github.com/marcinmilewicz/lumberjack-firestore-driver), custom log driver for `ngworker/lumberjack`. It sends logs and stores them in [Cloud Firestore](https://f
```suggestion
- [LumberjackFirestoreDriver](https://github.com/marcinmilewicz/lumberjack-firestore-driver), community log driver using [Cloud Firestore](https://firebase.google.com/docs/firestore) as a log store.
```

2021-01-21 22:19 UTC, LayZeeDK commented on README.md
> +This is a list of some recommended Lumberjack community drivers.
```suggestion
```

2021-01-21 22:19 UTC, LayZeeDK commented on README.md
> +Every log can be represented as a combination of its level, creation time, message, and scope. Using inline logs with the `LumberjackService` can cause structure duplication and-or de-standardization
Mention log payload.

2021-01-21 22:23 UTC, LayZeeDK commented on README.md
> +| Inline logs with `LumberjackService`            | Low                  | Create your logs inline in the `LumberjackService#log` method.                                                             |
I think we should remove this. A home-made rating system feels a bit tacky 😄

2021-01-21 22:27 UTC, LayZeeDK commented on README.md
> -This is the abstract interface of `LumberjackLogger`:
I didn't mean `interface`, I meant *interface* as in *API* 🙂

2021-01-21 22:29 UTC, LayZeeDK commented on README.md
> +Continue reading to know more about the recommended best practice.
```suggestion
Continue reading to know more about the recommended best practices.
```

2021-01-21 22:30 UTC, LayZeeDK commented on README.md
> +The result `AppLogger` after refactoring to using the `ScopedLumberjackLogger` would be
```suggestion
The resulting `AppLogger` after refactoring to using the `ScopedLumberjackLogger` would be:
```

2021-01-21 23:57 UTC, NachoVazquez commented on README.md
> +For example, we could use the default logging levels for the console driver and the critical and error levels for the **HTTP driver** as seen in the following example.
> Where did you catch this obsession with putting words in **bold**? 🤔😄

Who knows, it is my tick I guess 😅

2021-01-23 00:58 UTC, LayZeeDK requested changes
Wait for #64 and a second review.

Document `LumberjackLogFactory`.

2021-01-25 20:54 UTC, LayZeeDK commented on README.md
> +```
I think we should replace this section with `LumberjackLogFactory`.

2021-01-25 20:55 UTC, LayZeeDK commented on README.md
> +For example, we could use the default logging levels for the console driver and the critical and error levels for the **HTTP driver** as seen in the following example.
Can we remove the bold, please? It's distracting 🧐

2021-01-25 21:01 UTC, LayZeeDK requested changes

2021-01-25 21:01 UTC, LayZeeDK commented on README.md
> +Continue reading to know more about the recommended best practices designed to tackle this issues.
```suggestion
Continue reading to know more about the recommended best practices designed to tackle this issue.
```

2021-01-26 05:56 UTC, santoshyadavdev requested changes

2021-01-26 05:56 UTC, santoshyadavdev commented on README.md
> +You can use the `LumberjackService` by directly passing logs to its `log` method for short or simple use cases.However, we recommend implementing application-specific logger services instead. See the
You can use the `LumberjackService` by directly passing logs to its `log` method for short or simple use cases. However, we recommend implementing application-specific logger services instead. See the [_Best practices_](#best-practices) section.

2021-01-26 05:56 UTC, santoshyadavdev commented on README.md
> +There is nothing special about it. The only remarkable thing is that the config is passed down its constructor and assigned to the public `config` property. Lumberjack uses this configuration to dete
Maybe something like `In the above code snippet, the config is passed down its constructor and assigned to the public `config` property in the above code snippet. Lumberjack uses this configuration to determine which logs the driver should handle.` the problem is we are trying to say there is nothing special, which relates to either its magic or too easy.

2021-01-26 05:56 UTC, santoshyadavdev commented on README.md
> +This is possible because the `ConsoleDriver` has the same configuration options as the `LumberjackLogDriverConfig`. We only have to include the driver identifier since it cannot be predefined.
This is possible because the `ConsoleDriver` has the same configuration options as the `LumberjackLogDriverConfig`. You only have to include the driver identifier since it cannot be predefined.

2021-01-26 05:56 UTC, santoshyadavdev commented on README.md
> +By extending `LumberjackLogger`, we only have to worry about our pre-defined logs' message and scope.
By extending `LumberjackLogger`, you only have to worry about our pre-defined logs' message and scope.

2021-01-26 05:56 UTC, santoshyadavdev commented on README.md
> +Now that we have defined our first Lumberjack logger let's use it to log logs from our application.
Now that you have defined our first Lumberjack logger let's use it to log logs from our application.

2021-01-26 05:56 UTC, santoshyadavdev commented on README.md
> +As seen in the [Log drivers](#log-drivers) section, we can send extra info to our drivers using a `LumberjackLog#payload`.
As seen in the [Log drivers](#log-drivers) section, you can send extra info to our drivers using a `LumberjackLog#payload`.

2021-01-26 05:56 UTC, santoshyadavdev commented on README.md
> +However, there are some times that we want to create logs manullly and pass them to the `LumberjackService`.
However, there are some times that we want to create logs manually and pass them to the `LumberjackService`.

2021-01-26 05:56 UTC, santoshyadavdev commented on README.md
> +This is how we create logs manually:
This is how you create logs manually:

2021-01-26 09:50 UTC, LayZeeDK commented on README.md
> +You can use the `LumberjackService` by directly passing logs to its `log` method for short or simple use cases.However, we recommend implementing application-specific logger services instead. See the
I prefer the original structure of the sentence.

2021-01-26 18:41 UTC, NachoVazquez commented on README.md
> +You can use the `LumberjackService` by directly passing logs to its `log` method for short or simple use cases.However, we recommend implementing application-specific logger services instead. See the
What do you mean @LayZeeDK? The one in red??

What are you saying here @santoshyadavdev ? I don't see any difference between what you wrote and what it is already there.

2021-01-26 20:24 UTC, LayZeeDK commented on README.md
> +You can use the `LumberjackService` by directly passing logs to its `log` method for short or simple use cases.However, we recommend implementing application-specific logger services instead. See the
I liked the red better.

2021-01-26 21:37 UTC, LayZeeDK commented on README.md
> +By extending `LumberjackLogger`, you only have to worry about our pre-defined logs' message and scope.
Revert to "we".

2021-01-27 21:28 UTC, LayZeeDK requested changes

2021-01-27 21:28 UTC, LayZeeDK commented on README.md
> +Your driver may need some extra data not provided by the `LumberjackLog`.
```suggestion
We might want to add some extra data not present in the `LumberjackLog` to our log driver.
```

2021-01-27 21:28 UTC, LayZeeDK commented on README.md
> +Then you can start logging. However, you'll also want to inject `LumberjackTimeService` to maintain a high level of testability.
```suggestion
Then we can start logging. However, you'll also want to inject `LumberjackTimeService` to maintain a high level of testability.
```

2021-01-27 21:28 UTC, LayZeeDK commented on README.md
> +Lumberjack's configuration is flexible. You can provide a full configuration object, a partial option set, or no options at all.
```suggestion
Lumberjack's configuration is flexible. We can provide a full configuration object, a partial option set, or no options at all.
```

2021-01-27 21:28 UTC, LayZeeDK commented on README.md
> +When the `levels` setting is not configured, log levels are configured depending on whether your application runs in development mode or production mode.
```suggestion
When the `levels` setting is not configured, log levels are configured depending on whether our application runs in development mode or production mode.
```

2021-01-27 21:28 UTC, LayZeeDK commented on README.md
> +Every log can be represented as a combination of its level, creation time, message, scope and payload. Using inline logs with the `LumberjackService` can cause structure duplication and-or de-standar
```suggestion
Every log can be represented as a combination of its level, creation time, message, scope and payload. Using inline logs with the `LumberjackService` can cause structure duplication and/or denormalization.
```

2021-01-27 21:28 UTC, LayZeeDK commented on README.md
> +  }
Not needed for understanding. In fact, only needed for View Engine-compatibility.
```suggestion
```

2021-01-27 21:28 UTC, LayZeeDK commented on README.md
> +Lumberjack recommended way of creating logs is by using a `LumberjackLogger`.
```suggestion
Lumberjack's recommended way of creating logs is by using a `LumberjackLogger`.
```

2021-01-28 09:26 UTC, LayZeeDK requested changes

2021-01-28 09:26 UTC, LayZeeDK commented on README.md
> +In the above snippet the config is passed down its constructor and assigned to the public `config` property. Lumberjack uses this configuration to determine which logs the driver should handle.
```suggestion
In the above snippet, the config is passed down its constructor and assigned to the public `config` property. Lumberjack uses this configuration to determine which logs the log driver should handle.
```

2021-01-28 09:27 UTC, LayZeeDK commented
Apply suggestion, rebase/merge, then we're good to go, @NachoVazquez.

2021-01-28 14:16 UTC, LayZeeDK approved these changes

2021-01-28 14:16 UTC, merged