feat: add LumberjackLogFactory
ngworker/lumberjack pull request #64
Opened 2021-01-21 21:42 UTC by LayZeeDK

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[x] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?
Using `LumberjackLogBuilder` requires passing `LumberjackTimeService` to maintain testability. This can be cumbersome.

Issue Number: N/A

## What is the new behavior?
`LumberjackLogFactory` removes the need to having to inject and pass `LumberjackTimeService`.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-01-21 22:48 UTC, NachoVazquez requested changes
It makes the test much cleaner.

I missed a test file for the factory.

2021-01-21 22:48 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log-factory.ts
> +export class LumberjackLogFactory<TPayload extends LumberjackLogPayload | void = void> {
Should we document it a bit?

2021-01-21 22:51 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log-factory.ts
> +export class LumberjackLogFactory<TPayload extends LumberjackLogPayload | void = void> {
For sure! But I wanted your feedback on the validity of this idea first 😃

2021-01-21 22:52 UTC, LayZeeDK commented
> I missed a test file for the factory.
Indeed. I wanted your feedback on this concept first 🙂

2021-01-23 00:52 UTC, LayZeeDK commented
I added inline docs. Let's add docs in README in the docs review branch after merging.

2021-01-25 18:47 UTC, NachoVazquez requested changes

2021-01-25 18:47 UTC, NachoVazquez commented on libs/ngworker/lumberjack/src/lib/logging/lumberjack-log-factory.spec.ts
> +  });
Maybe a check that the payload is undefined when not passed.
```suggestion
  describe('Payload', () => {
    interface TestPayload extends LumberjackLogPayload {
      readonly test: boolean;
    }

    beforeEach(() => {
      logFactoryWithPayload = resolveDependency(LumberjackLogFactory);
      logFactoryWithoutPayload = resolveDependency(LumberjackLogFactory);
    });

    let logFactoryWithPayload: LumberjackLogFactory<TestPayload>;
    let logFactoryWithoutPayload: LumberjackLogFactory;

    it('creates a log with a static payload', () => {
      const log = logFactoryWithPayload.createErrorLog(testMessage).withPayload({ test: true }).build();

      expect(log.payload?.test).toBe(true);
    });

    it('creates a log with a dynamic payload', () => {
      const log = logFactoryWithPayload.createInfoLog(testMessage).build({ test: true });

      expect(log.payload?.test).toBe(true);
    });

    it('creates a log without a payload', () => {
      const log = logFactoryWithoutPayload.createInfoLog(testMessage).build();

      expect(log.payload).toBeUndefined();
    });
  });
    
     it('creates a log without payload', () => {
      const log = logFactoryWithPayload.createInfoLog(testMessage).build();

      expect(log.payload?.test).toBe(true);
    });
  });
```

2021-01-25 21:51 UTC, NachoVazquez approved these changes

2021-01-25 21:55 UTC, merged