Add schematics
ngworker/lumberjack pull request #70
Opened 2021-01-30 18:39 UTC by santoshyadavdev

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2021-01-30 23:52 UTC, LayZeeDK requested changes

2021-01-30 23:52 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/spy-driver/spy.driver.ts
> +};
These should be moved to separate files and exported in the public API.

2021-01-31 00:57 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/spy-driver/spy.driver.ts
> +};
I removed them and replaced their usage in test suites.

2021-01-31 11:15 UTC, LayZeeDK requested changes

2021-01-31 11:15 UTC, LayZeeDK commented on libs/internal/console-driver/test-util/src/lib/spy-console/spy-console.service.ts
> +    jest.clearAllMocks();
This affects all Jest mocks. We should be able to do without this.

2021-01-31 22:36 UTC, LayZeeDK requested changes

2021-01-31 22:36 UTC, LayZeeDK commented on package.json
> +    "build:lib": "ng build ngworker-lumberjack --prod && yarn build:schematics && npx copy README.md ./dist/ngworker/lumberjack",
I'm pretty sure we replaced `npx copy README.md` with an `angular.json`-based assets solution in `main`.

2021-01-31 22:36 UTC, LayZeeDK commented on package.json
> +    "jest-date-mock": "^1.0.8",
Are we stil using this dependency, @NachoVazquez? I don't see any of its API used. If used, add it to `devDependencies`. If not, remove it.

2021-01-31 22:36 UTC, LayZeeDK commented on package.json
> +    "ng-packagr": "^11.0.3",
I think we updated `ng-packagr` to 11.1.x in `main`.

2021-01-31 22:55 UTC, LayZeeDK requested changes

2021-01-31 22:55 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/error-throwing-driver/error-throwing-driver.module.ts
> +    throw new Error('ErrorThrowingDriverModule must guard against being imported directly');
Merge gone wrong. Revert this change.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/noop-driver/noop-driver.module.ts
> +    throw new Error('NoopDriverModule must guard against being imported directly');
Merge gone wrong. Revert this change.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/object-driver/object-driver.module.ts
> +    throw new Error('ObjectDriverModule must guard against being imported directly');
Merge gone wrong. Revert this change.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/internal/test-util/src/lib/spy-driver/spy-driver.module.ts
> +    throw new Error('SpyDriverModule must guard against being imported directly');
Merge gone wrong. Revert this change.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-root.module.spec.ts
> +    );
Merge gone wrong. Revert this change.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver-root.module.ts
> +      throw new Error('LumberjackConsoleDriverModule must guard against being imported directly');
Merge gone wrong. Revert this change.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/console-driver/src/lib/configuration/lumberjack-console-driver.module.ts
> +    throw new Error('LumberjackConsoleDriverModule must guard against being imported directly');
Merge gone wrong. Revert this change.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
>          // tslint:disable-next-line: no-any
Remove this TSLint exception.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
>          // tslint:disable-next-line: no-any
Remove this TSLint exception.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
>          // tslint:disable-next-line: no-any
Remove this TSLint exception.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
>          // tslint:disable-next-line: no-any
Remove this TSLint exception.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
> +      expect(actualConfig).toMatchObject(expectedConfig);
`toEqual` should be fine here.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
>          // tslint:disable-next-line: no-any
Remove this TSLint exception.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
>          // tslint:disable-next-line: no-any
Remove this TSLint exception.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/http-driver/src/lib/configuration/lumberjack-http-driver.module.spec.ts
> +      expect(actualConfig).toMatchObject(expectedConfig);
`toEqual` should be fine here.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configuration/lumberjack.module.spec.ts
> +      expect(actualConfig).toMatchObject({
`toEqual` should be fine here.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configuration/lumberjack.module.spec.ts
> +      expect(actualConfig).toMatchObject({
`toEqual` should be fine here.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/configuration/lumberjack.module.ts
> +    throw new Error('LumberjackModule must guard against being imported directly');
Merge gone wrong. Revert this change.

2021-01-31 22:55 UTC, LayZeeDK commented on libs/ngworker/lumberjack/src/lib/logging/scoped-lumberjack-logger.service.spec.ts
> +  // let lumberjackStub: jest.Mocked<LumberjackService>;
Remove this line.
```suggestion
```

2021-01-31 22:55 UTC, LayZeeDK commented on test-config.helper.ts
> +};
Is this file used anywhere?

2021-02-01 12:01 UTC, LayZeeDK commented
Commits 4602686-f4e49a5 broke schematic tests.

2021-02-01 18:22 UTC, NachoVazquez commented on libs/internal/console-driver/test-util/src/lib/spy-console/spy-console.service.ts
> +    jest.clearAllMocks();
Do you mean the last line right?

`jest.clearAllMocks();`

Replacing that with `this.debug.mockClear();` makes all test pass again.

2021-02-01 18:23 UTC, NachoVazquez commented on package.json
> +    "build:lib": "ng build ngworker-lumberjack --prod && yarn build:schematics && npx copy README.md ./dist/ngworker/lumberjack",
I don't remember that but if it is not there, I'll add it.

2021-02-01 18:42 UTC, NachoVazquez commented on package.json
> +    "build:lib": "ng build ngworker-lumberjack --prod && yarn build:schematics && npx copy README.md ./dist/ngworker/lumberjack",
Well, I can't make it work

https://github.com/ng-packagr/ng-packagr/blob/master/docs/copy-assets.md

I'll try again later.

2021-02-01 20:44 UTC, LayZeeDK commented on package.json
> +    "build:lib": "ng build ngworker-lumberjack --prod && yarn build:schematics && npx copy README.md ./dist/ngworker/lumberjack",
You're right, it probably doesn't support files outside of its projectRoot since it's not as advanced as the Angular application builder.

@santoshyadavdev your assets copy for schematics is not working either. What do we need to do to bundle schematics?

2021-02-01 20:46 UTC, LayZeeDK commented
@NachoVazquez Please resolve the change requests you addressed.

2021-02-02 13:45 UTC, LayZeeDK commented on README.md
> +The `ng add` command will add the below code to your module.
It will also add the console driver by default.

2021-02-03 00:55 UTC, LayZeeDK commented
In the `schematics-e2e` job when using Angular 9.0, the following warning is displayed and the matrix leg fails:
> ts-jest[versions] (WARN) Version 3.7.5 of typescript installed has not been tested with ts-jest. If you're experiencing issues, consider using a supported version (>=3.8.0 <5.0.0-0). Please do not report issues in ts-jest if you are using unsupported versions.

2021-02-03 20:56 UTC, LayZeeDK approved these changes

2021-02-03 20:57 UTC, merged