docs: add @agroupp as a contributor
ngworker/lumberjack pull request #82
Opened 2021-02-23 15:18 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[x] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Arthur Groupp is not on the All Contributors list.

Issue Number: N/A

## What is the new behavior?

Arthur Groupp is on the All Contributors list for his idea regarding the Lumberjack Payload.

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-02-23 15:23 UTC, LayZeeDK requested changes

2021-02-23 15:23 UTC, LayZeeDK commented on README.md
> +    <td align="center"><a href="https://indepth.dev/author/layzee/"><img src="https://avatars1.githubusercontent.com/u/6364586?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Lars Gyrup Brink Nielsen
Please keep my link as `https://dev.to/layzee/`. I guess it should be changed in `.all-contributorsrc`.

2021-02-23 15:24 UTC, NachoVazquez commented on README.md
> +    <td align="center"><a href="https://indepth.dev/author/layzee/"><img src="https://avatars1.githubusercontent.com/u/6364586?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Lars Gyrup Brink Nielsen
Yes, I will fix it in both places!

2021-02-23 15:29 UTC, SerkanSipahi approved these changes
LGTM!

2021-02-23 15:48 UTC, SerkanSipahi approved these changes
LGTM 💯

2021-02-23 15:52 UTC, santoshyadavdev approved these changes
LGTM

2021-02-24 13:07 UTC, LayZeeDK approved these changes

2021-02-24 13:23 UTC, merged