feat: create logger schematics
ngworker/lumberjack pull request #83
Opened 2021-02-25 11:59 UTC by santoshyadavdev

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Issue Number: N/A

## What is the new behavior?

## Does this PR introduce a breaking change?

```
[ ] Yes
[ ] No
```

## Other information

2021-03-12 11:39 UTC, LayZeeDK commented
This is the uncovered conditional, SonarCloud is unhappy about:
https://sonarcloud.io/code?id=ngworker_lumberjack&pullRequest=83&selected=ngworker_lumberjack%3Alibs%2Fngworker%2Flumberjack%2Fschematics%2Flog-driver%2Flog-driver.ts&line=29

2021-03-12 12:13 UTC, santoshyadavdev commented
> This is the uncovered conditional SonarCloud is unhappy about:
> https://sonarcloud.io/code?id=ngworker_lumberjack&pullRequest=83&selected=ngworker_lumberjack%3Alibs%2Fngworker%2Flumberjack%2Fschematics%2Flog-driver%2Flog-driver.ts&line=29

Yeah still in WIP as I wanted some confirmation from Nacho, the tests need to be changed a little.

2021-03-12 13:40 UTC, NachoVazquez requested changes

2021-03-12 13:40 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/__name@dasherize__-driver-config.token.ts.template
> +export const myLogDriverConfigToken = new InjectionToken<LumberjackLogDriverConfig>('__MY_LOG_DRIVER_CONFIG__', {
Can we obtain the name of the driver from prompt and use it here instead of myLogDriver?

2021-03-12 13:40 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/__name@dasherize__-driver-config.token.ts.template
> +export const myLogDriverConfigToken = new InjectionToken<LumberjackLogDriverConfig>('__MY_LOG_DRIVER_CONFIG__', {
Also, we are not using a factory in the Injection token anymore, maybe you used an old version of the drivers to create the schematics.

I would recommend using the HttpDriver as an example since it is the most complex one and therefore it would suit every scenario.

2021-03-12 13:40 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/__name@dasherize__-driver-config.token.ts.template
> +export const myLogDriverConfigToken = new InjectionToken<LumberjackLogDriverConfig>('__MY_LOG_DRIVER_CONFIG__', {
Apply the last comment to every file, "use the HTTP driver example"

2021-03-13 17:36 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/__name@dasherize__-driver-config.token.ts.template
> +export const myLogDriverConfigToken = new InjectionToken<LumberjackLogDriverConfig>('__MY_LOG_DRIVER_CONFIG__', {
Can you update here https://gist.github.com/LayZeeDK/3651c9f9d91696d67b635e4b03c14ff0

2021-04-04 13:40 UTC, santoshyadavdev commented
https://gist.github.com/NachoVazquez/7229b25359cb6963c2678f464b985182

2021-04-11 15:26 UTC, NachoVazquez requested changes
There are some inconsistencies about the lumberjack prefix. Let's fix that and I'll perform a second review after that.

I'm very excited about this feature, great work! 🙂

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/collection.json
> +      "description": "Create a logger service"
I think this is not accurate we are creating a log driver, a logger service is a different thing to Lumberjack

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-config.token.spec.ts.template
> +import { lumberjack<%= classify(name) %>DriverConfigToken } from './lumberjack-<%= dasherize(name) %>-driver-config.token';
Just to be on the same page, are we forcing again the "lumberjack" prefix. 
If not, we should make it part of the <%= classify(name) %>

Same thing in the file-name.

Be aware that my suggestion may not work because it may start with a capital letter.

```suggestion
import { <%= classify(name) %>DriverConfigToken } from './-<%= dasherize(name) %>-driver-config.token';
```

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-config.token.spec.ts.template
> +  identifier: 'TestCustomDriver',
We might want a more accurate identifier here, something like

`Test<%= classify(name) %>Driver`

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-config.token.spec.ts.template
> +          { provide: lumberjack<%= classify(name) %>DriverConfigToken, useValue: debugDriverConfig },
Same as before, we might not want to force the lumberjack prefix.

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-config.token.spec.ts.template
> +      const actualDriverConfig = resolveDependency(lumberjack<%= classify(name) %>DriverConfigToken);
Lumberjack prefix!.

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-config.token.ts.template
> +);
Lumberjack prefix and also in the filename

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-config.ts.template
> +  Partial<Pick<LumberjackLogDriverConfig, 'identifier'>>;
Lumberjack prefix, and also in the filename

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-root.module.spec.ts.template
> +});
Lumberjack prefix and also in the filename. 

I'm suspecting that you rollback what we discussed for some reason 🙂

2021-04-11 15:26 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-root.module.ts.template
> +import { <%= classify(name) %>Driver } from '../log-drivers/<%= dasherize(name) %>-driver';
And now you are not using the lumberjack prefix 😄. 

Please make this consistent across the solution, lets make the review incremental, I'll take another look once that is ready.

2021-04-15 17:43 UTC, LayZeeDK commented
I made this addition to the `afterEach` hook of `ng-generate.spec.ts`:
```ts
execSync('git clean --force -- apps/lumberjack-schematics-app', {
  stdio: 'inherit',
});
```

Before we merge, we should extract the common test staging from `ng-add.spec.ts` and `ng-generate.spec.ts` so that it can be reused and in sync between all schematics end-to-end tests.

2021-04-16 23:09 UTC, LayZeeDK commented
> I made this addition to the `afterEach` hook of `ng-generate.spec.ts` to clean up untracked (generated) files:
> 
> ```ts
> execSync('git clean --force -- apps/lumberjack-schematics-app', {
>   stdio: 'inherit',
> });
> ```
> 
> Before we merge, we should extract the common test staging from `ng-add.spec.ts` and `ng-generate.spec.ts` so that it can be reused and in sync between all schematics end-to-end tests.

Did this test refactoring.

2021-04-17 16:10 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/lumberjack-__name@dasherize__-driver-config.token.spec.ts.template
> +import { lumberjack<%= classify(name) %>DriverConfigToken } from './lumberjack-<%= dasherize(name) %>-driver-config.token';
This schematic is meant for project-specific log drivers. I changed the templates and expectations so that we don't require a Lumberjack prefix.

2021-04-26 19:29 UTC, LayZeeDK requested changes
@santoshyadavdev
Nice feature! Please make sure to complete the following:
- Update README with the schematic and its options
- Fill out the PR description

2021-04-26 20:59 UTC, LayZeeDK requested changes
Found this issue when trying out the `log-driver` schematic in a live stream.

2021-04-26 20:59 UTC, LayZeeDK commented on apps/schematics-e2e/src/e2e/log-driver/golden-files/configuration/console-driver-root.module.ts.golden
> +  const fullConfig = { ...baseConfig, ...customDriverConfig };
issue: The golden file is wrong here.
```suggestion
  const fullConfig = { ...baseConfig, ...consoleDriverConfig };
```

2021-04-26 20:59 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/__name@dasherize__-driver-root.module.ts.template
> +  const fullConfig = { ...baseConfig, ...customDriverConfig };
issue: Match the parameter name.
```suggestion
  const fullConfig = { ...baseConfig, ...<%= camelize(name) %>DriverConfig };
```

2021-04-26 21:23 UTC, LayZeeDK requested changes

2021-04-26 21:23 UTC, LayZeeDK commented on apps/schematics-e2e/src/e2e/log-driver/golden-files/configuration/console-driver-config.token.spec.ts.golden
> +      expect(actualDriverConfig).toStrictEqual(debugDriverConfig);
issue: use `toBe` to be compatible with both Jest, Jasmine, and Karma.
```suggestion
      expect(actualDriverConfig).toBe(debugDriverConfig);
```

2021-04-26 21:23 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/__name@dasherize__-driver-config.token.spec.ts.template
> +      expect(actualDriverConfig).toStrictEqual(debugDriverConfig);
issue: use `toBe` to be compatible with both Jest, Jasmine, and Karma.
```suggestion
      expect(actualDriverConfig).toBe(debugDriverConfig);
```

2021-04-26 21:23 UTC, LayZeeDK commented on apps/schematics-e2e/src/e2e/log-driver/golden-files/configuration/console-driver.module.spec.ts.golden
> +  config?: consoleDriverConfig;
issue: This should refer to a type, not a variable.
```suggestion
  config?: ConsoleDriverConfig;
```

2021-04-26 21:23 UTC, LayZeeDK commented on libs/ngworker/lumberjack/schematics/log-driver/files/__name@dasherize@if-flat__/configuration/__name@dasherize__-driver.module.spec.ts.template
> +  config?: <%= camelize(name) %>DriverConfig;
issue: This should refer to a type, not a variable.
```suggestion
  config?: <%= classify(name) %>DriverConfig;
```

2021-04-26 21:29 UTC, LayZeeDK commented
@santoshyadavdev
As agreed, please rename the generated folder name to `<name>-driver`, for example if I run:
```
ng generate @ngworker/lumberjack:log-driver console
```

I should see a folder `console-driver` with the two subfolders `configuration` and `log-drivers`.

2021-05-01 18:34 UTC, santoshyadavdev commented
> @santoshyadavdev
> Nice feature! Please make sure to complete the following:
> 
> * Review available schematic options
> * Update README with details about the schematic and its options
> * Fill out the PR description
> * Rebase this branch on top of `main`

Done will above 3 , going to rebase wish me luck 😂

2021-05-01 18:42 UTC, santoshyadavdev commented
> > @santoshyadavdev
> > Nice feature! Please make sure to complete the following:
> > 
> > * Review available schematic options
> > * Update README with details about the schematic and its options
> > * Fill out the PR description
> > * Rebase this branch on top of `main`
> 
> Done with above 3 , going to rebase wish me luck 😂

@LayZeeDK I am done with rebase 😂

2021-05-01 19:49 UTC, LayZeeDK commented
Make sure to also address the 6 changes I requested 🙂

2021-05-01 19:50 UTC, santoshyadavdev commented
> Make sure to also address the 6 changes I requested 🙂

Included them too 😊

2021-05-02 20:09 UTC, NachoVazquez requested changes
Everything is looking great, I left a few notes. I will try to do a second review later.

2021-05-02 20:09 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/schema.json
> +      "description": "The name of the logger.",
Should this description be the same as the name description?

2021-05-09 16:33 UTC, santoshyadavdev commented on libs/ngworker/lumberjack/schematics/log-driver/files/__rootFolder@dasherize@if-flat__/configuration/__name@dasherize__-driver-config.token.spec.ts.template
> +  identifier: 'Test<%= classify(name) %>Driver',
I think its as per https://gist.github.com/NachoVazquez/7229b25359cb6963c2678f464b985182#file-lumberjack-custom-driver-configuration-lumberjack-custom-driver-module-spec-ts-L53 can you confirm what it should be?

2021-05-15 17:20 UTC, NachoVazquez requested changes
We are really close 🤩

2021-05-15 17:20 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__rootFolder@dasherize@if-flat__/configuration/__name@dasherize__-driver-config.token.spec.ts.template
> +  identifier: 'Test<%= classify(name) %>Driver',
Yeah, sorry about that 🙂. I think just keeping the name without the prefix is ok.

2021-05-15 17:20 UTC, NachoVazquez commented on libs/ngworker/lumberjack/schematics/log-driver/files/__rootFolder@dasherize@if-flat__/configuration/__name@dasherize__-driver.module.spec.ts.template
> +        identifier: 'Test<%= classify(name) %>Driver',
Let's take the "Test" out here aswell!

2021-05-23 16:35 UTC, santoshyadavdev commented
Done @NachoVazquez

2021-09-01 20:17 UTC, LayZeeDK commented
@santoshyadavdev said
> For schematic we have an issues as V12 deprecared some APIs

2021-09-08 18:50 UTC, santoshyadavdev commented
@LayZeeDK @NachoVazquez I need some help here, looks like jest related issues here with tests

2023-06-03 14:36 UTC, NachoVazquez commented
closing this because it has been open for 2 years now. we can definitely come back and take ideas from here in the future

2023-06-03 14:36 UTC, closed without merging