ci: add support for angular 12 and node 14
ngworker/lumberjack pull request #86
Opened 2021-04-25 13:51 UTC by NachoVazquez

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [x] Tests for the changes have been added (for bug fixes / features)
- [x] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[x] CI related changes
[ ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Lumberjack CI is not verifying support for Angular v12

Issue Number: N/A

## What is the new behavior?

Lumberjack CI is verifying support for Angular v12

## Does this PR introduce a breaking change?

```
[ ] Yes
[x] No
```

## Other information

2021-04-25 14:59 UTC, LayZeeDK requested changes

2021-04-25 14:59 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
You've added Node.js `14.x` for Angular 9.0.x-11.2.x. That won't work.

2021-04-25 15:00 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
This is what we need
```yml
        node-version: [10.x, 12.x]
        angular-version: [9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x, 11.1.x, 11.2.x]
        include:
          - node-version: 14.x
            angular-version: 12.0.x
```

2021-04-25 15:09 UTC, LayZeeDK requested changes

2021-04-25 15:09 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +  NODE_LATEST: 14.x
1. We can't make this change without updating dependencies in `package.json`.
2. We shouldn't update dependencies before an Angular 12.0 stable release.

2021-04-25 15:10 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +  NODE_LATEST: 14.x
Consider renaming these variables to `ANGULAR_LATEST_STABLE` and `NODE_LATEST_COMPATIBLE`.

2021-04-25 15:19 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
Why it won't work?

It is working

2021-04-25 15:21 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
Because Angular <12.0.x doesn't have official support for Node.js 14.x and we don't want anything to break because of this.

2021-04-25 15:21 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
If it works, it's accidental not intentional. As we add more features, we'll eventually get errors because of this.

2021-04-25 15:22 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
OK!

2021-04-25 15:24 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
I think include doesn't work that way, it only includes previously excluded version, but I will take a look I might be wrong.

2021-04-25 15:26 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
Nop, you are right, that works.

2021-04-25 16:13 UTC, LayZeeDK requested changes

2021-04-25 16:13 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +  NODE_LATEST_STABLE: 12.x
This name is no better than `NODE_LATEST` since we know it's neither the latest, nor the latest stable. Either roll back this change or find a name that expresses that it's the latest Node.js version supported by the latest stable version of Angular.

2021-04-25 16:13 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +      - name: Use Node.js ${{ env.NODE_LATEST_STABLE }}
We should either:
A. Change this one to 12.x explicitly since it's the only version that is supported by all the listed versions of Angular
B. Use the Node.js version supported by each individual Angular version which means Node.js 14.x for Angular 12.0.x, 12.x for other Angular versions.

2021-04-25 16:13 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x, 11.1.x, 11.2.x, 12.0.x]
Same comment as for the `lib` job applies.

2021-04-25 16:17 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +  NODE_LATEST_STABLE: 12.x
NODE_DEFAULT ??

2021-04-25 16:17 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +      - name: Use Node.js ${{ env.NODE_LATEST_STABLE }}
Probably a combination of both, changing the name to NODE_DEFAULT and include a job for Angular 12.0.x and Node.js 14.x

2021-04-25 16:18 UTC, LayZeeDK requested changes

2021-04-25 16:18 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +  ANGULAR_LATEST_STABLE: 11.2.x
1) Add this comment to make it more clear.
```suggestion
  # must match the version in `package.json`
  ANGULAR_LATEST_STABLE: 11.2.x
```

2021-04-25 16:18 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +  ANGULAR_LATEST_STABLE: 11.2.x
2. Either update the dependencies in `package.json` or roll back this chagne.

2021-04-25 16:18 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +  NODE_LATEST_STABLE: 12.x
Also add this comment to make it more clear
```suggestion
  # The latest version supported by the Angular version listed in `ANGULAR_LATEST_STABLE`.
  NODE_LATEST_STABLE: 12.x
```

2021-04-25 16:18 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +      - name: Use Node.js ${{ env.NODE_LATEST_STABLE }}
I suggest we change the variable names to `NODE_CURRENT` and `ANGULAR_CURRENT` with the comments I suggested.

2021-04-25 16:19 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        node-version: [10.x, 12.x, 14.x]
Yes, `include` can be worked with or without `exclude`.

2021-04-25 16:22 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +      - name: Use Node.js ${{ env.NODE_LATEST_STABLE }}
I think we should avoid duplicate jobs. It's better to use `matrix` configurations so that jobs don't become out-of-sync.

2021-04-25 17:16 UTC, NachoVazquez commented on .github/workflows/ci.yml
> +      - name: Use Node.js ${{ env.NODE_LATEST_STABLE }}
Yeah, sorry I meant a matrix parameter when I said job.

2021-04-25 17:18 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +  NODE_LATEST_STABLE: 12.x
We could also delete these variables if they are too confusing but we would lose some speed because we can't restore the exact cache.

2021-04-25 20:02 UTC, LayZeeDK requested changes

2021-04-25 20:02 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +            angular-version: 12.0.x
suggestion: Use this format for consistency:
```suggestion
        include:
          - angular-version: 12.0.x
            node-version: 14.x
```

2021-04-25 20:02 UTC, LayZeeDK commented on package.json
> +    "@angular/core": "~11.2.11",
question: Were there any migrations?

2021-04-25 20:31 UTC, NachoVazquez commented on package.json
> +    "@angular/core": "~11.2.11",
Nop, it makes sense it was just a minor.

2021-04-25 20:37 UTC, LayZeeDK commented on package.json
> +    "@angular/core": "~11.2.11",
Did you already forget the 9.x->10.0->10.1 💩 show?

2021-04-25 20:43 UTC, LayZeeDK requested changes

2021-04-25 20:43 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +            angular-version: 12.0.x
suggestion: Use this format for consistency:
```suggestion
          - angular-version: 12.0.x
            node-version: 14.x
```

2021-04-25 20:43 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x, 11.1.x, 11.2.x, 12.0.x]
suggestion: Remove 12.0.x from this list. No need to test it twice.
```suggestion
        angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x, 11.1.x, 11.2.x]
```

2021-04-25 20:43 UTC, LayZeeDK commented on .github/workflows/ci.yml
> +        angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x, 11.1.x, 11.2.x, 12.0.x]
suggestion: Remove 12.0.x from this list. No need to test it twice.
```suggestion
        angular-version: [9.0.x, 9.1.x, 10.0.x, 10.1.x, 10.2.x, 11.0.x, 11.1.x, 11.2.x]
```

2021-04-25 22:31 UTC, LayZeeDK commented on package.json
>      "@angular-devkit/build-ng-packagr": "~0.1002.1",
We should be removing this one and using `@angular-devkit/build-angular:ng-packagr` instead but we would have to wait for https://github.com/ngworker/angular-versions-action/pull/22 for our CI to work.

2021-04-25 22:33 UTC, LayZeeDK commented on package.json
>      "@angular-devkit/build-ng-packagr": "~0.1002.1",
Can you put this task in a card, @NachoVazquez?

2021-04-25 22:35 UTC, LayZeeDK requested changes

2021-04-25 22:35 UTC, LayZeeDK commented on package.json
> +    "@angular-devkit/build-angular": "^0.1102.10",
suggestion: Use version ranges that are not going to get us into trouble when Angular 12 is released.
```suggestion
    "@angular-builders/jest": "~11.2.0",
    "@angular-devkit/build-angular": "~0.1102.10",
```

2021-04-25 23:01 UTC, NachoVazquez commented on package.json
> +    "@angular-devkit/build-angular": "^0.1102.10",
Like what it had before?

2021-04-25 23:06 UTC, NachoVazquez commented on package.json
>      "@angular-devkit/build-ng-packagr": "~0.1002.1",
Yes, sure. But I think that the older builder is used by @santosh for the schematics. Unless that changed.

2021-04-26 13:21 UTC, santoshyadavdev commented on package.json
>      "@angular-devkit/build-ng-packagr": "~0.1002.1",
Ahh you tagged the wrong Santosh @NachoVazquez 😁

2021-04-26 19:11 UTC, LayZeeDK commented on package.json
>      "@angular-devkit/build-ng-packagr": "~0.1002.1",
@NachoVazquez
Nope, schematics use `tsc` directly, see the `build:schematics` script in `package.json`.

2021-04-26 19:14 UTC, santoshyadavdev commented on package.json
>      "@angular-devkit/build-ng-packagr": "~0.1002.1",
Yes schematic use `tsc` probably if i added those builders, it may be during the phase when I was trying several builders 🤦‍♂️

2021-04-26 19:25 UTC, LayZeeDK submitted a review, later dismissed

2021-04-26 20:50 UTC, merged