docs: fix http driver readme link
ngworker/lumberjack pull request #90
Opened 2021-06-03 17:48 UTC by SergeyCherman

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ X] The commit message follows our guidelines: CONTRIBUTING.md#commit
- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

## PR Type

What kind of change does this PR introduce?

```
[ ] Bugfix
[ ] Feature
[ ] Code style update (formatting, local variables)
[ ] Refactoring (no functional changes, no api changes)
[ ] Build related changes
[ ] CI related changes
[X ] Documentation content changes
[ ] Other... Please describe:
```

## What is the current behavior?

Currently the link http driver readme goes to a page not found.

Issue Number: N/A

## What is the new behavior?
Updated the http driver link in the main readme to point to the http driver readme in libs.

## Does this PR introduce a breaking change?

```
[ ] Yes
[X ] No
```

## Other information

2021-06-03 17:52 UTC, NachoVazquez approved these changes
Thank you! And welcome to Lumberjack 😀

2021-06-03 21:27 UTC, LayZeeDK requested changes

2021-06-03 21:27 UTC, LayZeeDK commented on README.md
> +For a more advanced log driver implementation, see [LumberjackHttpDriver](https://github.com/ngworker/lumberjack/blob/main/libs/ngworker/lumberjack/http-driver/README.md)
Let's add a comma to trigger another CI workflow run. A secret for SonarCloud was missing or expired. It should be fixed now.
```suggestion
For a more advanced log driver implementation, see [LumberjackHttpDriver](https://github.com/ngworker/lumberjack/blob/main/libs/ngworker/lumberjack/http-driver/README.md).
```

2021-06-03 21:29 UTC, LayZeeDK commented
@all-contributors add @SergeyCherman for docs

2021-06-03 22:01 UTC, LayZeeDK commented
We're having some issues because of security protections. We need to modify our GitHub workflows to allow this PR. Please have patience a few days.

2021-06-03 22:04 UTC, SergeyCherman commented
No worries, thanks for the fast review.

2021-06-10 20:12 UTC, NachoVazquez commented
> No worries, thanks for the fast review.

We are facing some limitations with Github Actions. While we reach a solution, could you please create the PR from a clone of the original repository instead of your fork?

2021-06-20 20:32 UTC, LayZeeDK approved these changes

2021-06-20 20:43 UTC, closed without merging